CREATE TABLE `translations` (
	`locale` text NOT NULL,
	`key` text NOT NULL,
	`value` text NOT NULL,
	`created_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	PRIMARY KEY(`locale`, `key`)
);
--> statement-breakpoint
CREATE INDEX `translations_locale_idx` ON `translations` (`locale`);
--> statement-breakpoint
INSERT INTO `translations` (`locale`, `key`, `value`)
VALUES
('tr', 'common.languageLabel', 'Dil'),
('tr', 'common.localeSwitcherAriaLabel', 'Dil degistir'),
('tr', 'common.locale.tr', 'TR'),
('tr', 'common.locale.en', 'EN'),
('tr', 'common.dismiss', 'Kapat'),
('tr', 'common.roleGuard', 'Rol korumasi'),
('tr', 'common.active', 'AKTIF'),
('tr', 'common.inactive', 'PASIF'),
('tr', 'common.edit', 'Duzenle'),
('tr', 'common.delete', 'Sil'),
('tr', 'common.deactivate', 'Pasiflestir'),
('tr', 'site.name', 'Enes Ink'),
('tr', 'site.title.home', 'Enes Ink | Edge-First Portfolyo ve Notlar'),
('tr', 'site.title.projects', 'Projeler | Enes Ink'),
('tr', 'site.title.blog', 'Blog | Enes Ink'),
('tr', 'site.title.blogPostFallback', 'Blog Yazisi | Enes Ink'),
('tr', 'site.title.login', 'Dashboard girisi | Enes Ink'),
('tr', 'site.description.home', 'Cloudflare uzerinde calisan, performans odakli portfolyo ve teknik blog sistemi.'),
('tr', 'site.description.projects', 'Secili projeler, teknik ozetler ve uygulama notlari.'),
('tr', 'site.description.blog', 'Edge-first teknik notlar, mimari denemeler ve uygulama gunlukleri.'),
('tr', 'site.description.login', 'Yonetim paneline erisim icin Better Auth ile korunan giris sayfasi.'),
('tr', 'root.error.eyebrow', 'Beklenmeyen durum'),
('tr', 'root.error.title', 'Sayfa yuklenemedi.'),
('tr', 'root.error.body', 'Istek islenirken bir hata olustu. Bu temel iskelet sonraki adimlarda zenginlestirilecek.'),
('tr', 'public.layout.footerCaption', 'Edge-first notlar, piksel sertliginde arayuzler ve gerektiginden fazla kahve.'),
('tr', 'public.layout.footerCta', 'Yukariya don'),
('tr', 'public.layout.footerEyebrow', 'Paper / Ink / Code'),
('tr', 'public.layout.footerName', 'Enes Ink'),
('tr', 'public.layout.footerYear', '© 2026'),
('tr', 'public.layout.navBlog', 'Blog'),
('tr', 'public.layout.navHome', 'Ana sayfa'),
('tr', 'public.layout.navMenuLabel', 'Navigasyonu degistir'),
('tr', 'public.layout.navMenuText', 'Menu'),
('tr', 'public.layout.navProjects', 'Projeler'),
('tr', 'public.layout.navResume', 'Ozgecmis'),
('tr', 'public.layout.themeDarkLabel', 'Comic Noir'),
('tr', 'public.layout.themeLightLabel', 'Paper Comic'),
('tr', 'public.layout.themeToggle', 'Tema'),
('tr', 'public.layout.social.github', 'GitHub'),
('tr', 'public.layout.social.linkedin', 'LinkedIn'),
('tr', 'public.layout.social.mail', 'Mail'),
('tr', 'public.home.availability', 'Secili freelance ve urun is birlikleri icin uygunum.'),
('tr', 'public.home.ctaBody', 'Keskin karakteri olan ve teslimati guvenilir bir portfolyo, teknik blog, dashboard veya editor akisi mi gerekiyor?'),
('tr', 'public.home.ctaEyebrow', 'Is birligi / Teslimat / Bakim'),
('tr', 'public.home.ctaPrimary', 'Proje baslatalim'),
('tr', 'public.home.ctaSecondary', 'Bloga git'),
('tr', 'public.home.ctaTitle', 'Bilincli Hissettiren Bir Sey Insa Edelim.'),
('tr', 'public.home.featuredEyebrow', 'Secili Isler'),
('tr', 'public.home.featuredTitle', 'One Cikan Projeler'),
('tr', 'public.home.heroBadge', '2016''dan beri Edge-First'),
('tr', 'public.home.heroBody', 'React Router, Cloudflare ve TypeScript ile keskin dijital urunler tasarlayip yayina aliyorum. Odak noktasi hiz, erisebilirlik ve yayindan sonra da okunabilir kalan sistemler.'),
('tr', 'public.home.heroPrimary', 'Projeleri gor'),
('tr', 'public.home.heroSecondary', 'Ozgecmisi ac'),
('tr', 'public.home.heroTitle', 'Merhaba, ben Enes. Kodla ise yarar seyler uretiyorum.'),
('tr', 'public.home.resumeBody', 'Guclu performans ve surdurulebilirlik kisitlari altinda urun sistemleri, admin akislari ve editor platformlarina odaklanan senior full-stack muhendis.'),
('tr', 'public.home.resumeCta', 'PDF ozgecmis iste'),
('tr', 'public.home.resumeEyebrow', 'Profil / Ozgecmis / Sinyaller'),
('tr', 'public.home.resumeMetaLabel', 'Mevcut odak'),
('tr', 'public.home.resumeTitle', 'Ozgecmis Ozeti'),
('tr', 'public.home.socialTitle', 'Webde Ben'),
('tr', 'public.home.techEyebrow', 'Moduller yuklendi'),
('tr', 'public.home.techTitle', 'Teknoloji Yigini'),
('tr', 'public.home.visualCommand', 'deploy --edge --typed --accessible'),
('tr', 'public.home.visualLabel', 'Paper Comic Runtime'),
('tr', 'public.home.highlight.1', 'SSR-first route mimarisi'),
('tr', 'public.home.highlight.2', 'Erisilebilir neo-brutalist arayuzler'),
('tr', 'public.home.highlight.3', 'Cloudflare-native deploy akislari'),
('tr', 'public.home.metric.focus.label', 'Odak'),
('tr', 'public.home.metric.focus.value', 'Edge Uygulamalar'),
('tr', 'public.home.metric.stack.label', 'Stack'),
('tr', 'public.home.metric.stack.value', 'React Router'),
('tr', 'public.home.metric.style.label', 'Stil'),
('tr', 'public.home.metric.style.value', 'Neo-Brutal'),
('tr', 'public.home.metric.systemLabel', 'Sistem'),
('tr', 'public.home.metric.systemValue', 'Hazir'),
('tr', 'public.home.featuredProjects.browseAll', 'Tum proje islerini incele'),
('tr', 'public.home.featuredProjects.featuredSince', 'One cikan'),
('tr', 'public.home.featuredProjects.liveCta', 'Canli surum'),
('tr', 'public.home.featuredProjects.projectsCta', 'Projeleri ac'),
('tr', 'public.home.featuredProjects.repoCta', 'Repo gor'),
('tr', 'public.home.social.github.label', 'GitHub'),
('tr', 'public.home.social.github.description', 'Kod, deneyler ve uygulama detaylari.'),
('tr', 'public.home.social.linkedin.label', 'LinkedIn'),
('tr', 'public.home.social.linkedin.description', 'Profesyonel profil, deneyim ve network.'),
('tr', 'public.home.social.mail.label', 'E-posta'),
('tr', 'public.home.social.mail.description', 'Proje talepleri, ozgecmis istekleri ve dogrudan iletisim.'),
('tr', 'public.home.resumePoint.1', 'Full-stack urun muhendisligi'),
('tr', 'public.home.resumePoint.2', 'Admin workflow tasarimi'),
('tr', 'public.home.resumePoint.3', 'Performans ve SEO guclendirmesi'),
('tr', 'public.home.resumePoint.4', 'Teknik yazi sistemleri'),
('tr', 'public.home.resumeMeta.basedIn.label', 'Konum'),
('tr', 'public.home.resumeMeta.basedIn.value', 'Istanbul / Remote'),
('tr', 'public.home.resumeMeta.workingWith.label', 'Calistigim ekipler'),
('tr', 'public.home.resumeMeta.workingWith.value', 'Founderlar, ajanslar, urun ekipleri'),
('tr', 'public.home.resumeMeta.delivery.label', 'Teslimat'),
('tr', 'public.home.resumeMeta.delivery.value', 'Design system, uygulama ve icerik platformlari'),
('tr', 'public.home.resumeFocusValue', 'urun sistemleri, dashboardlar, yayinlama'),
('tr', 'public.home.availabilityLabel', 'Uygunluk'),
('tr', 'public.home.runtimeCommandLabel', 'Runtime komutu'),
('tr', 'public.home.techDescription', 'Urunun keskin routing, typed sozlesmeler ve productionda sikici kalacak deploy akislari istemesi durumunda ilk uzandigim temel araclar.'),
('tr', 'public.projects.emptyBody', 'Yayinlanmis proje kartlari ilk public case study hazir olur olmaz burada gorunecek.'),
('tr', 'public.projects.emptyEyebrow', 'Proje Kayitlari'),
('tr', 'public.projects.emptyTitle', 'Henuz public proje yok.'),
('tr', 'public.projects.feedLoading', 'Sonraki set yukleniyor...'),
('tr', 'public.projects.feedReady', 'Daha fazla proje icin asagi kaydir'),
('tr', 'public.projects.featuredBadge', 'One cikan'),
('tr', 'public.projects.heroBody', 'Hizli route yapilari, net veri sozlesmeleri ve surdurulebilir teslimat icin uretilmis arayuzlerin, icerik sistemlerinin ve dashboard akislarinin public kaydi.'),
('tr', 'public.projects.heroEyebrow', 'Secili Buildler / Public Kayit'),
('tr', 'public.projects.heroTitle', 'Keskin Koseyle Uretilen Projeler.'),
('tr', 'public.projects.liveCta', 'Canli build'),
('tr', 'public.projects.repoCta', 'Kaynak kod'),
('tr', 'public.projects.scrollHint', 'Asagi kaydikca otomatik yukleme devam eder.'),
('tr', 'public.projects.statFeatured', 'One cikan'),
('tr', 'public.projects.statLive', 'Canli link'),
('tr', 'public.projects.statTotal', 'Yayinlanan'),
('tr', 'public.projects.techLabel', 'Stack odagi'),
('tr', 'public.blog.archiveCaption', 'Ayni kagit masadan yayinlanmis notlar, postmortemler ve deploy kayitlari.'),
('tr', 'public.blog.archiveEyebrow', 'Public logbook'),
('tr', 'public.blog.archiveTitle', 'Edge Tarafindan Alan Notlari'),
('tr', 'public.blog.authorLabel', 'Yazar'),
('tr', 'public.blog.authorFallbackBio', 'Edge-native uygulamalar ve editor deneyimi etrafinda calisiyor.'),
('tr', 'public.blog.backToBlog', 'Bloga don'),
('tr', 'public.blog.emptyBody', 'Public notlar su anda duzenleniyor. Editor hatti hazir, ancak yayinlanmis bir hikaye henuz yok.'),
('tr', 'public.blog.emptyTitle', 'Defter henuz kuruyor'),
('tr', 'public.blog.feedLoading', 'Sonraki set yukleniyor...'),
('tr', 'public.blog.feedReady', 'Daha fazla not icin asagi kaydir'),
('tr', 'public.blog.moreNotesTitle', 'Daha fazla not'),
('tr', 'public.blog.notebookIndexTitle', 'Defter dizini'),
('tr', 'public.blog.recentTopicsTitle', 'Son basliklar'),
('tr', 'public.blog.readTimeSuffix', 'dk okuma'),
('tr', 'public.blog.scrollHint', 'Asagi kaydikca otomatik yukleme devam eder.'),
('tr', 'public.blog.updatedLabel', 'Guncellendi'),
('tr', 'public.blog.topic.1', 'Cloudflare'),
('tr', 'public.blog.topic.2', 'React Router'),
('tr', 'public.blog.topic.3', 'D1'),
('tr', 'public.blog.topic.4', 'Editorial UX'),
('tr', 'public.blog.topic.5', 'Observability'),
('tr', 'public.blog.topic.6', 'Deploy Notes'),
('tr', 'login.adminBadge', 'Admin'),
('tr', 'login.buildLabel', 'Build: v2.4.2-stable'),
('tr', 'login.buttonIdle', 'Terminale_Gir'),
('tr', 'login.buttonSubmitting', 'Giris_Yapiliyor...'),
('tr', 'login.emailLabel', 'E-posta'),
('tr', 'login.emailPlaceholder', 'ADMIN_USER@INK.DEV'),
('tr', 'login.footerSecurity', 'HttpOnly / Secure / SameSite=Lax'),
('tr', 'login.heading', 'Erisim'),
('tr', 'login.headingHighlight', 'Sadece'),
('tr', 'login.headingTail', 'Adminlere Acik'),
('tr', 'login.nodeLabel', 'Node: TR-IST-01'),
('tr', 'login.passwordLabel', 'Parola'),
('tr', 'login.returnToSite', 'Siteye_Don'),
('tr', 'login.securityDescription', 'Session izleme aktif. Yetkisiz denemeler kayda gecirilecek.'),
('tr', 'login.securityLevel', 'Guvenlik Seviyesi: Alpha'),
('tr', 'login.siteName', 'Paper Enes Ink'),
('tr', 'dashboard.layout.navDashboard', 'Dashboard'),
('tr', 'dashboard.layout.navPosts', 'Yazilar'),
('tr', 'dashboard.layout.navProjects', 'Projeler'),
('tr', 'dashboard.layout.navSkills', 'Beceriler'),
('tr', 'dashboard.layout.navUsers', 'Kullanicilar'),
('tr', 'dashboard.layout.navSettings', 'Ayarlar'),
('tr', 'dashboard.layout.navStatusLive', 'Canli'),
('tr', 'dashboard.layout.navStatusLater', 'Sonra'),
('tr', 'dashboard.layout.closeMenuAriaLabel', 'Navigasyon menusunu kapat'),
('tr', 'dashboard.layout.closeOverlayAriaLabel', 'Navigasyon kaplamasini kapat'),
('tr', 'dashboard.layout.logoutAriaLabel', 'Mevcut admin oturumunu kapat'),
('tr', 'dashboard.layout.logoutLabel', 'Cikis yap'),
('tr', 'dashboard.layout.menuOpenAriaLabel', 'Navigasyon menusunu ac'),
('tr', 'dashboard.layout.navigationAriaLabel', 'Dashboard'),
('tr', 'dashboard.layout.shellTitle', 'Admin Portal'),
('tr', 'dashboard.layout.shellVersion', 'V1.0.4-stable'),
('tr', 'dashboard.layout.statusDescription', 'Oturum guvende / dashboard kabugu aktif'),
('tr', 'dashboard.layout.statusTitle', 'Sistem Durumu: Giris yapildi'),
('tr', 'dashboard.layout.roleAccessSuffix', 'erisim'),
('tr', 'dashboard.projects.createActionLabel', 'Yeni proje olustur'),
('tr', 'dashboard.projects.createDescription', 'Yeni bir proje olustur ve dashboard kaydina ekle.'),
('tr', 'dashboard.projects.createTitle', 'Proje olustur'),
('tr', 'dashboard.projects.editActionLabel', 'Projeyi guncelle'),
('tr', 'dashboard.projects.editDescription', 'Mevcut proje kaydini guncelle ve degisiklikleri server tarafinda kaydet.'),
('tr', 'dashboard.projects.editTitle', 'Projeyi duzenle'),
('tr', 'dashboard.projects.emptyState', 'Henuz proje eklenmedi.'),
('tr', 'dashboard.projects.featuredLabel', 'One cikan'),
('tr', 'dashboard.projects.featuredToggleLabel', 'One cikan proje'),
('tr', 'dashboard.projects.inventoryEyebrow', 'Canli envanter'),
('tr', 'dashboard.projects.registryTitle', 'Proje kayitlari'),
('tr', 'dashboard.projects.tableActionsLabel', 'Aksiyonlar'),
('tr', 'dashboard.projects.tableNameLabel', 'Proje adi'),
('tr', 'dashboard.projects.tableStatusLabel', 'Durum'),
('tr', 'dashboard.projects.tableSummaryLabel', 'Ozet'),
('tr', 'dashboard.projects.metricTotal', 'Toplam proje'),
('tr', 'dashboard.projects.metricFeatured', 'One cikan node'),
('tr', 'dashboard.projects.metricLive', 'Canli link'),
('tr', 'dashboard.projects.form.cancelLabel', 'Iptal'),
('tr', 'dashboard.projects.form.coverImageUrl.label', 'Kapak gorseli URL'),
('tr', 'dashboard.projects.form.coverImageUrl.placeholder', 'https://images...'),
('tr', 'dashboard.projects.form.description.label', 'Aciklama'),
('tr', 'dashboard.projects.form.error.deleteMissingProject', 'Silinecek proje bulunamadi.'),
('tr', 'dashboard.projects.form.error.updateMissingProject', 'Duzenlenecek proje bulunamadi.'),
('tr', 'dashboard.projects.form.liveUrl.label', 'Canli URL'),
('tr', 'dashboard.projects.form.liveUrl.placeholder', 'https://project.example'),
('tr', 'dashboard.projects.form.repositoryUrl.label', 'Repository URL'),
('tr', 'dashboard.projects.form.repositoryUrl.placeholder', 'https://github.com/...'),
('tr', 'dashboard.projects.form.slug.label', 'Slug'),
('tr', 'dashboard.projects.form.slug.placeholder', 'cyber-store-front'),
('tr', 'dashboard.projects.form.sortOrder.label', 'Siralama'),
('tr', 'dashboard.projects.form.sortOrder.placeholder', '0'),
('tr', 'dashboard.projects.form.status.label', 'Durum'),
('tr', 'dashboard.projects.form.summary.label', 'Ozet'),
('tr', 'dashboard.projects.form.summary.placeholder', 'Retro bir vitrin icin edge-first commerce arayuzu.'),
('tr', 'dashboard.projects.form.title.label', 'Proje adi'),
('tr', 'dashboard.projects.form.title.placeholder', 'CYBER_STORE_FRONT'),
('tr', 'dashboard.posts.createActionLabel', 'Yeni yazi olustur'),
('tr', 'dashboard.posts.createDescription', 'Yayin hattina yeni bir hikaye ekle ve durumunu dashboard icinden yonet.'),
('tr', 'dashboard.posts.composeEyebrow', 'Taslak / Yerelde kaydedildi'),
('tr', 'dashboard.posts.createTitle', 'Yazi olustur'),
('tr', 'dashboard.posts.editActionLabel', 'Yaziyi guncelle'),
('tr', 'dashboard.posts.editDescription', 'Mevcut hikayenin govdesini, yayin tarihini ve durumunu guncelle.'),
('tr', 'dashboard.posts.editTitle', 'Yaziyi duzenle'),
('tr', 'dashboard.posts.emptyState', 'Henuz yazi yok. Ilk hikayeni ekle.'),
('tr', 'dashboard.posts.inventoryEyebrow', 'Yayin hatti'),
('tr', 'dashboard.posts.publishedLabel', 'Yayinda'),
('tr', 'dashboard.posts.registryTitle', 'Yazi kayitlari'),
('tr', 'dashboard.posts.tableActionsLabel', 'Aksiyonlar'),
('tr', 'dashboard.posts.tableNameLabel', 'Yazi adi'),
('tr', 'dashboard.posts.tableStatusLabel', 'Durum'),
('tr', 'dashboard.posts.tableSummaryLabel', 'Ozet'),
('tr', 'dashboard.posts.metricTotal', 'Toplam yazi'),
('tr', 'dashboard.posts.metricPublished', 'Yayindaki yazilar'),
('tr', 'dashboard.posts.metricDraft', 'Taslak kuyrugu'),
('tr', 'dashboard.posts.form.backToListLabel', 'Yazilara don'),
('tr', 'dashboard.posts.form.closeFullscreenLabel', 'Editoru kapat'),
('tr', 'dashboard.posts.form.content.label', 'Yazi govdesi'),
('tr', 'dashboard.posts.form.content.placeholder', 'Hikayeni anlat...'),
('tr', 'dashboard.posts.form.coverImageUrl.label', 'Kapak gorseli URL'),
('tr', 'dashboard.posts.form.coverImageUrl.placeholder', 'https://cdn.paper-portfolio-ink.dev/posts/edge-cache.webp'),
('tr', 'dashboard.posts.form.error.deleteMissingPost', 'Silinecek yazi bulunamadi.'),
('tr', 'dashboard.posts.form.error.missingAuthor', 'Aktif kullanici cozulemedi. Tekrar giris yap.'),
('tr', 'dashboard.posts.form.error.updateMissingPost', 'Duzenlenecek yazi kimligi eksik.'),
('tr', 'dashboard.posts.form.editor.imagePromptLabel', 'Gorsel adresini gir'),
('tr', 'dashboard.posts.form.editor.linkPromptLabel', 'Baglanti adresini gir'),
('tr', 'dashboard.posts.form.editor.loadingLabel', 'Editor hazirlaniyor...'),
('tr', 'dashboard.posts.form.editor.urlDefaultValue', 'https://'),
('tr', 'dashboard.posts.form.excerpt.label', 'Ozet'),
('tr', 'dashboard.posts.form.excerpt.placeholder', 'Yazinin liste ekraninda gosterilecek kisa ozeti.'),
('tr', 'dashboard.posts.form.fullscreenTitlePlaceholder', 'Hikayeni anlat...'),
('tr', 'dashboard.posts.form.heroHelper', 'Minimal yazim akisini koruyup yayin metadata bilgisini sag panelde yonet.'),
('tr', 'dashboard.posts.form.publishedAt.label', 'Yayin tarihi'),
('tr', 'dashboard.posts.form.slug.label', 'Slug'),
('tr', 'dashboard.posts.form.slug.placeholder', 'edge-cache-rollout'),
('tr', 'dashboard.posts.form.status.label', 'Durum'),
('tr', 'dashboard.posts.form.title.label', 'Yazi basligi'),
('tr', 'dashboard.posts.form.title.placeholder', 'Edge Cache Rollout Notes'),
('tr', 'dashboard.posts.composeTitle', 'Yaz'),
('tr', 'dashboard.posts.setupTitle', 'Yazi kurulumu'),
('tr', 'dashboard.posts.flowTitle', 'Editor akisi'),
('tr', 'dashboard.posts.createdLabel', 'Olusturuldu'),
('tr', 'dashboard.posts.updatedLabel', 'Guncellendi'),
('tr', 'dashboard.posts.publishedAtLabel', 'Yayinda'),
('tr', 'dashboard.skills.actionBlockedTitle', 'Aksiyon engellendi'),
('tr', 'dashboard.skills.createActionLabel', 'Beceri olustur'),
('tr', 'dashboard.skills.createDescription', 'Portfolyo skill kaydi olustur; daha sonra public stack yuzeylerinde tekrar kullanilabilsin.'),
('tr', 'dashboard.skills.createTitle', 'Beceri olustur'),
('tr', 'dashboard.skills.currentRoleLabel', 'Mevcut rol'),
('tr', 'dashboard.skills.editActionLabel', 'Beceri guncelle'),
('tr', 'dashboard.skills.editDescription', 'Mevcut becerinin ikon, ozet ve siralama bilgisini guncelle.'),
('tr', 'dashboard.skills.editTitle', 'Beceri duzenle'),
('tr', 'dashboard.skills.emptyState', 'Henuz beceri kaydi yok.'),
('tr', 'dashboard.skills.inventoryEyebrow', 'Portfolyo taksonomisi'),
('tr', 'dashboard.skills.registryTitle', 'Beceri kayitlari'),
('tr', 'dashboard.skills.restrictedDescription', 'Bu flow icin erisim yetkiniz yoktur.'),
('tr', 'dashboard.skills.restrictedTitle', 'Kisitli akis'),
('tr', 'dashboard.skills.metricTotal', 'Toplam beceri'),
('tr', 'dashboard.skills.tableActionsLabel', 'Aksiyonlar'),
('tr', 'dashboard.skills.tableCreatedLabel', 'Olusturuldu'),
('tr', 'dashboard.skills.tableIconLabel', 'Ikon'),
('tr', 'dashboard.skills.tableNameLabel', 'Beceri'),
('tr', 'dashboard.skills.tableSortLabel', 'Sira'),
('tr', 'dashboard.skills.tableSlugLabel', 'Anahtar'),
('tr', 'dashboard.skills.tableSummaryLabel', 'Ozet'),
('tr', 'dashboard.skills.generatedKeyLabel', 'Uretilen anahtar'),
('tr', 'dashboard.skills.generatedKeyPlaceholder', 'Gecerli bir beceri adi bekleniyor'),
('tr', 'dashboard.skills.selectedIconLabel', 'Secilen ikon'),
('tr', 'dashboard.skills.form.cancelLabel', 'Iptal'),
('tr', 'dashboard.skills.form.error.createDuplicateSkill', 'Bu beceri zaten kayitli.'),
('tr', 'dashboard.skills.form.error.deleteMissingSkill', 'Silinecek beceri bulunamadi.'),
('tr', 'dashboard.skills.form.error.forbidden', 'Bu flow icin erisim yetkiniz yoktur.'),
('tr', 'dashboard.skills.form.error.updateDuplicateSkill', 'Bu beceri baska bir kayitta zaten kullanimda.'),
('tr', 'dashboard.skills.form.error.updateMissingSkill', 'Guncellenecek beceri bulunamadi.'),
('tr', 'dashboard.skills.form.iconKey.label', 'Ikon'),
('tr', 'dashboard.skills.form.name.label', 'Beceri adi'),
('tr', 'dashboard.skills.form.name.placeholder', 'Cloudflare D1'),
('tr', 'dashboard.skills.form.sortOrder.label', 'Siralama'),
('tr', 'dashboard.skills.form.sortOrder.placeholder', '0'),
('tr', 'dashboard.skills.form.summary.label', 'Ozet'),
('tr', 'dashboard.skills.form.summary.placeholder', 'Kuresel urun sistemleri icin edge veritabani workflowlari.'),
('tr', 'dashboard.users.actionBlockedTitle', 'Aksiyon engellendi'),
('tr', 'dashboard.users.createActionLabel', 'Yeni kullanici olustur'),
('tr', 'dashboard.users.createDescription', 'Rol kapsamli erisimle birlikte credential tabanli dashboard kullanicisi olustur.'),
('tr', 'dashboard.users.createTitle', 'Kullanici olustur'),
('tr', 'dashboard.users.currentRoleLabel', 'Mevcut rol'),
('tr', 'dashboard.users.editActionLabel', 'Kullaniciyi guncelle'),
('tr', 'dashboard.users.editDescription', 'Kimlik alanlarini guncelle, rol yetkisini degistir veya parola rotasyonu yap.'),
('tr', 'dashboard.users.editTitle', 'Kullaniciyi duzenle'),
('tr', 'dashboard.users.emptyState', 'Henuz dashboard kullanicisi yok.'),
('tr', 'dashboard.users.inventoryEyebrow', 'Erisim kontrolu'),
('tr', 'dashboard.users.registryTitle', 'Kullanici kayitlari'),
('tr', 'dashboard.users.restrictedDescription', 'Bu flow icin erisim yetkiniz yoktur.'),
('tr', 'dashboard.users.restrictedTitle', 'Kisitli akis'),
('tr', 'dashboard.users.selfLabel', 'Sen'),
('tr', 'dashboard.users.metricTotal', 'Toplam kullanici'),
('tr', 'dashboard.users.metricAdmin', 'Admin koltugu'),
('tr', 'dashboard.users.metricAuthor', 'Yazar koltugu'),
('tr', 'dashboard.users.tableActionsLabel', 'Aksiyonlar'),
('tr', 'dashboard.users.tableIdentityLabel', 'Kimlik'),
('tr', 'dashboard.users.tableMetaLabel', 'Meta'),
('tr', 'dashboard.users.tableRoleLabel', 'Rol'),
('tr', 'dashboard.users.metaCreatedPrefix', 'Olusturuldu'),
('tr', 'dashboard.users.metaUpdatedPrefix', 'Guncellendi'),
('tr', 'dashboard.users.metaAvatarBound', 'Avatar bagli'),
('tr', 'dashboard.users.metaNoAvatar', 'Avatar yok'),
('tr', 'dashboard.users.metaSessionEnabled', 'Oturum etkin'),
('tr', 'dashboard.users.metaSessionDisabled', 'Oturum devre disi'),
('tr', 'dashboard.shared.dismiss', 'Kapat'),
('tr', 'dashboard.users.form.avatarUrl.label', 'Avatar URL'),
('tr', 'dashboard.users.form.avatarUrl.placeholder', 'https://images.paper-portfolio-ink.dev/avatar.webp'),
('tr', 'dashboard.users.form.bio.label', 'Biyografi'),
('tr', 'dashboard.users.form.bio.placeholder', 'Dashboard ekibi icin kisa operasyonel baglam.'),
('tr', 'dashboard.users.form.cancelLabel', 'Iptal'),
('tr', 'dashboard.users.form.displayName.label', 'Gorunen ad'),
('tr', 'dashboard.users.form.displayName.placeholder', 'Ayla Author'),
('tr', 'dashboard.users.form.email.label', 'E-posta'),
('tr', 'dashboard.users.form.email.placeholder', 'author@paper-portfolio-ink.dev'),
('tr', 'dashboard.users.form.error.createDuplicateEmail', 'Bu e-posta adresi zaten kullanimda.'),
('tr', 'dashboard.users.form.error.deactivateMissingUser', 'Pasiflestirilecek kullanici bulunamadi.'),
('tr', 'dashboard.users.form.error.forbidden', 'Bu flow icin erisim yetkiniz yoktur.'),
('tr', 'dashboard.users.form.error.lastActiveAdminDeactivate', 'Son aktif admin hesabi pasiflestirilemez.'),
('tr', 'dashboard.users.form.error.lastActiveAdminDemotion', 'Son aktif admin hesabi author rolune dusurulemez.'),
('tr', 'dashboard.users.form.error.lastActiveAdminDelete', 'Son aktif admin hesabi kaldirilamaz.'),
('tr', 'dashboard.users.form.error.updateDuplicateEmail', 'Bu e-posta adresi baska bir kullaniciya ait.'),
('tr', 'dashboard.users.form.error.updateMissingUser', 'Guncellenecek kullanici bulunamadi.'),
('tr', 'dashboard.users.form.password.editHint', 'Bos birakilirsa mevcut parola korunur.'),
('tr', 'dashboard.users.form.password.label', 'Parola'),
('tr', 'dashboard.users.form.password.placeholder', 'PaperInk1234!'),
('tr', 'dashboard.users.form.role.label', 'Rol'),
('tr', 'dashboard.users.form.statusLabel', 'Hesabi aktif tut'),
('tr', 'dashboard.overview.stat.totalPosts.label', 'Toplam yazi'),
('tr', 'dashboard.overview.stat.totalViews.label', 'Toplam goruntulenme'),
('tr', 'dashboard.overview.stat.projectSuccess.label', 'Proje basarisi'),
('tr', 'dashboard.overview.stat.serverLoad.label', 'Sunucu yuku'),
('tr', 'dashboard.overview.stat.stable', 'Stabil'),
('tr', 'dashboard.overview.stat.optimal', 'Optimal'),
('tr', 'dashboard.overview.post.1.category', 'Tasarim'),
('tr', 'dashboard.overview.post.1.status', 'Yayinda'),
('tr', 'dashboard.overview.post.1.title', 'UI Tasariminda Neo-Brutalism'),
('tr', 'dashboard.overview.post.2.category', 'Teknik'),
('tr', 'dashboard.overview.post.2.status', 'Taslak'),
('tr', 'dashboard.overview.post.2.title', 'Web Gelistirmenin 2024 Sonrasi'),
('tr', 'dashboard.overview.post.3.category', 'Egitim'),
('tr', 'dashboard.overview.post.3.status', 'Yayinda'),
('tr', 'dashboard.overview.post.3.title', 'Buyuk Projelerde CSS Olceklemek'),
('tr', 'dashboard.overview.log.1.time', '2 saat once'),
('tr', 'dashboard.overview.log.1.title', 'Blog yazisi guncellendi: UI Tasariminda Neo-Brutalism'),
('tr', 'dashboard.overview.log.2.time', 'Dun'),
('tr', 'dashboard.overview.log.2.title', 'Yeni proje eklendi: Edge Commerce'),
('tr', 'dashboard.overview.log.3.time', '3 gun once'),
('tr', 'dashboard.overview.log.3.title', 'Sistem konfigurasyonu degisti'),
('tr', 'model.projectStatus.draft', 'Taslak'),
('tr', 'model.projectStatus.published', 'Yayinda'),
('tr', 'model.projectStatus.archived', 'Arsivlendi'),
('tr', 'model.postStatus.draft', 'Taslak'),
('tr', 'model.postStatus.published', 'Yayinda'),
('tr', 'model.postStatus.archived', 'Arsivlendi'),
('tr', 'model.userRole.admin', 'Admin'),
('tr', 'model.userRole.author', 'Yazar'),
('tr', 'skillIcon.cloud.label', 'Cloud'),
('tr', 'skillIcon.cloud.description', 'Dagitik sistemler, edge servisleri ve platform teslimati.'),
('tr', 'skillIcon.database.label', 'Veritabani'),
('tr', 'skillIcon.database.description', 'Veritabani tasarimi, sorgu akislari ve depolama katmanlari.'),
('tr', 'skillIcon.code.label', 'Kod'),
('tr', 'skillIcon.code.description', 'Tip guvenli frontend ve backend implementasyon detaylari.'),
('tr', 'skillIcon.workflow.label', 'Workflow'),
('tr', 'skillIcon.workflow.description', 'Mimari birlestirme, orkestrasyon ve akis modelleme.'),
('tr', 'skillIcon.shield.label', 'Guvenlik'),
('tr', 'skillIcon.shield.description', 'Sistem guclendirme, guven sinirlari ve erisim kontrolu.'),
('tr', 'skillIcon.rocket.label', 'Lansman'),
('tr', 'skillIcon.rocket.description', 'Deploy hatlari, yayina hazirlik ve urun momentumu.'),
('tr', 'skillIcon.layers.label', 'Arayuz'),
('tr', 'skillIcon.layers.description', 'Bilesebilir UI sistemleri ve tekrar kullanilabilir primitive yuzeyler.'),
('tr', 'skillIcon.pen.label', 'Editorial'),
('tr', 'skillIcon.pen.description', 'Icerik sistemleri, editor araclari ve yazi workflowlari.'),
('tr', 'skillIcon.blocks.label', 'Moduller'),
('tr', 'skillIcon.blocks.description', 'Altyapi modulleri, platform parcalari ve ortak yapi taslari.'),
('tr', 'skillIcon.wrench.label', 'Operasyon'),
('tr', 'skillIcon.wrench.description', 'Operasyon, runtime bakimi ve pratik muhendislik isi.'),
('tr', 'skillIcon.globe.label', 'Web'),
('tr', 'skillIcon.globe.description', 'Public sistemler, erisim ve kuresel deneyimler.'),
('tr', 'validation.project.title.min', 'Proje basligi en az 3 karakter olmali.'),
('tr', 'validation.project.title.max', 'Proje basligi en fazla 80 karakter olabilir.'),
('tr', 'validation.project.slug.pattern', 'Slug sadece kucuk harf, rakam ve tire icerebilir.'),
('tr', 'validation.project.slug.min', 'Slug en az 3 karakter olmali.'),
('tr', 'validation.project.summary.min', 'Proje ozeti en az 12 karakter olmali.'),
('tr', 'validation.project.summary.max', 'Proje ozeti en fazla 180 karakter olabilir.'),
('tr', 'validation.project.description.max', 'Aciklama en fazla 3000 karakter olabilir.'),
('tr', 'validation.project.repositoryUrl', 'Gecerli bir repository URL gir.'),
('tr', 'validation.project.liveUrl', 'Gecerli bir live URL gir.'),
('tr', 'validation.project.coverImageUrl', 'Gecerli bir kapak gorseli URL gir.'),
('tr', 'validation.project.status', 'Gecerli bir yayin durumu sec.'),
('tr', 'validation.project.sortOrder.int', 'Siralama tam sayi olmali.'),
('tr', 'validation.project.sortOrder.min', 'Siralama degeri 0 veya daha buyuk olmali.'),
('tr', 'validation.post.title.min', 'Yazi basligi en az 3 karakter olmali.'),
('tr', 'validation.post.title.max', 'Yazi basligi en fazla 120 karakter olabilir.'),
('tr', 'validation.post.slug.pattern', 'Slug sadece kucuk harf, rakam ve tire icerebilir.'),
('tr', 'validation.post.slug.min', 'Slug en az 3 karakter olmali.'),
('tr', 'validation.post.excerpt.min', 'Ozet en az 12 karakter olmali.'),
('tr', 'validation.post.excerpt.max', 'Ozet en fazla 240 karakter olabilir.'),
('tr', 'validation.post.content.min', 'Yazi govdesi en az 20 karakter olmali.'),
('tr', 'validation.post.content.max', 'Yazi govdesi en fazla 100000 karakter olabilir.'),
('tr', 'validation.post.coverImageUrl', 'Gecerli bir kapak gorseli URL gir.'),
('tr', 'validation.post.status', 'Gecerli bir yayin durumu sec.'),
('tr', 'validation.skill.icon', 'Gecerli bir ikon sec.'),
('tr', 'validation.skill.name.min', 'Beceri adi en az 2 karakter olmali.'),
('tr', 'validation.skill.name.max', 'Beceri adi en fazla 48 karakter olabilir.'),
('tr', 'validation.skill.name.slug', 'Beceri adi gecerli bir anahtar uretemedi.'),
('tr', 'validation.skill.summary.min', 'Beceri ozeti en az 12 karakter olmali.'),
('tr', 'validation.skill.summary.max', 'Beceri ozeti en fazla 180 karakter olabilir.'),
('tr', 'validation.skill.sortOrder.int', 'Siralama tam sayi olmali.'),
('tr', 'validation.skill.sortOrder.min', 'Siralama degeri 0 veya daha buyuk olmali.'),
('tr', 'validation.user.avatarUrl', 'Gecerli bir avatar URL gir.'),
('tr', 'validation.user.bio.max', 'Biyografi en fazla 500 karakter olabilir.'),
('tr', 'validation.user.displayName.min', 'Gorunen ad en az 2 karakter olmali.'),
('tr', 'validation.user.displayName.max', 'Gorunen ad en fazla 80 karakter olabilir.'),
('tr', 'validation.user.email', 'Gecerli bir e-posta adresi gir.'),
('tr', 'validation.user.password.max', 'Parola en fazla 128 karakter olabilir.'),
('tr', 'validation.user.role', 'Gecerli bir kullanici rolu sec.'),
('tr', 'validation.user.password.createMin', 'Parola en az 8 karakter olmali.'),
('tr', 'validation.user.password.updateMin', 'Parola degistirilecekse en az 8 karakter olmali.'),
('tr', 'validation.login.email', 'Gecerli bir e-posta gir.'),
('tr', 'validation.login.password.min', 'Parola en az 8 karakter olmali.'),
('tr', 'validation.login.password.max', 'Parola en fazla 128 karakter olabilir.'),
('tr', 'validation.login.invalidCredentials', 'E-posta veya parola hatali.'),
('tr', 'validation.login.unavailable', 'Giris su anda tamamlanamadi.'),
('tr', 'validation.slug.taken', 'Bu slug zaten kullanimda. Baska bir slug sec.'),
('tr', 'aria.publicBlog.cover', 'kapak gorseli'),
('tr', 'aria.dashboardModal.closeOverlay', 'Dashboard modal kaplamasini kapat'),
('tr', 'aria.dashboardModal.close', 'Dashboard modalini kapat'),
('tr', 'aria.projects.edit', 'Duzenle'),
('tr', 'aria.projects.delete', 'Sil'),
('tr', 'aria.users.edit', 'Duzenle'),
('tr', 'aria.users.delete', 'Sil'),
('en', 'common.languageLabel', 'Language'),
('en', 'common.localeSwitcherAriaLabel', 'Switch language'),
('en', 'common.locale.tr', 'TR'),
('en', 'common.locale.en', 'EN'),
('en', 'common.dismiss', 'Dismiss'),
('en', 'common.roleGuard', 'Role guard'),
('en', 'common.active', 'ACTIVE'),
('en', 'common.inactive', 'INACTIVE'),
('en', 'common.edit', 'Edit'),
('en', 'common.delete', 'Delete'),
('en', 'common.deactivate', 'Deactivate'),
('en', 'site.name', 'Enes Ink'),
('en', 'site.title.home', 'Enes Ink | Edge-First Portfolio and Notes'),
('en', 'site.title.projects', 'Projects | Enes Ink'),
('en', 'site.title.blog', 'Blog | Enes Ink'),
('en', 'site.title.blogPostFallback', 'Blog Post | Enes Ink'),
('en', 'site.title.login', 'Dashboard login | Enes Ink'),
('en', 'site.description.home', 'Performance-focused portfolio and technical blog system running on Cloudflare.'),
('en', 'site.description.projects', 'Selected builds, technical summaries, and delivery notes.'),
('en', 'site.description.blog', 'Edge-first technical notes, architecture experiments, and build journals.'),
('en', 'site.description.login', 'Protected sign-in page for accessing the admin dashboard through Better Auth.'),
('en', 'root.error.eyebrow', 'Unexpected state'),
('en', 'root.error.title', 'The page could not be loaded.'),
('en', 'root.error.body', 'An error occurred while processing the request. This foundation will be expanded in the next steps.'),
('en', 'public.layout.footerCaption', 'Edge-first notes, pixel-sharp interfaces, and more coffee than required.'),
('en', 'public.layout.footerCta', 'Back to top'),
('en', 'public.layout.footerEyebrow', 'Paper / Ink / Code'),
('en', 'public.layout.footerName', 'Enes Ink'),
('en', 'public.layout.footerYear', '© 2026'),
('en', 'public.layout.navBlog', 'Blog'),
('en', 'public.layout.navHome', 'Home'),
('en', 'public.layout.navMenuLabel', 'Toggle navigation'),
('en', 'public.layout.navMenuText', 'Menu'),
('en', 'public.layout.navProjects', 'Projects'),
('en', 'public.layout.navResume', 'Resume'),
('en', 'public.layout.themeDarkLabel', 'Comic Noir'),
('en', 'public.layout.themeLightLabel', 'Paper Comic'),
('en', 'public.layout.themeToggle', 'Theme'),
('en', 'public.layout.social.github', 'GitHub'),
('en', 'public.layout.social.linkedin', 'LinkedIn'),
('en', 'public.layout.social.mail', 'Mail'),
('en', 'public.home.availability', 'Available for selected freelance and product collaborations.'),
('en', 'public.home.ctaBody', 'Need a portfolio, technical blog, dashboard, or editorial workflow with sharp edges and reliable delivery?'),
('en', 'public.home.ctaEyebrow', 'Collaboration / Shipping / Maintenance'),
('en', 'public.home.ctaPrimary', 'Start a project'),
('en', 'public.home.ctaSecondary', 'Read the blog'),
('en', 'public.home.ctaTitle', 'Build Something That Feels Deliberate.'),
('en', 'public.home.featuredEyebrow', 'Selected work'),
('en', 'public.home.featuredTitle', 'Featured projects'),
('en', 'public.home.heroBadge', 'Edge-First Since 2016'),
('en', 'public.home.heroBody', 'I design and ship sharp digital products with React Router, Cloudflare, and TypeScript. The focus is speed, accessibility, and systems that stay readable after launch.'),
('en', 'public.home.heroPrimary', 'View projects'),
('en', 'public.home.heroSecondary', 'Open resume'),
('en', 'public.home.heroTitle', 'Hello, I am Enes. I Build Useful Things With Code.'),
('en', 'public.home.resumeBody', 'Senior full-stack engineer focused on product systems, admin workflows, and editorial platforms with strong performance and maintainability constraints.'),
('en', 'public.home.resumeCta', 'Request PDF resume'),
('en', 'public.home.resumeEyebrow', 'Profile / Resume / Signals'),
('en', 'public.home.resumeMetaLabel', 'Current focus'),
('en', 'public.home.resumeTitle', 'Resume snapshot'),
('en', 'public.home.socialTitle', 'Around the web'),
('en', 'public.home.techEyebrow', 'Modules loaded'),
('en', 'public.home.techTitle', 'Tech stack'),
('en', 'public.home.visualCommand', 'deploy --edge --typed --accessible'),
('en', 'public.home.visualLabel', 'Paper Comic Runtime'),
('en', 'public.home.highlight.1', 'SSR-first route architecture'),
('en', 'public.home.highlight.2', 'Accessible neo-brutalist interfaces'),
('en', 'public.home.highlight.3', 'Cloudflare-native deployment workflows'),
('en', 'public.home.metric.focus.label', 'Focus'),
('en', 'public.home.metric.focus.value', 'Edge Apps'),
('en', 'public.home.metric.stack.label', 'Stack'),
('en', 'public.home.metric.stack.value', 'React Router'),
('en', 'public.home.metric.style.label', 'Style'),
('en', 'public.home.metric.style.value', 'Neo-Brutal'),
('en', 'public.home.metric.systemLabel', 'System'),
('en', 'public.home.metric.systemValue', 'Ready'),
('en', 'public.home.featuredProjects.browseAll', 'Browse all project work'),
('en', 'public.home.featuredProjects.featuredSince', 'Featured'),
('en', 'public.home.featuredProjects.liveCta', 'Open live build'),
('en', 'public.home.featuredProjects.projectsCta', 'Open projects'),
('en', 'public.home.featuredProjects.repoCta', 'View repo'),
('en', 'public.home.social.github.label', 'GitHub'),
('en', 'public.home.social.github.description', 'Code, experiments, and implementation details.'),
('en', 'public.home.social.linkedin.label', 'LinkedIn'),
('en', 'public.home.social.linkedin.description', 'Professional profile, experience, and network.'),
('en', 'public.home.social.mail.label', 'Email'),
('en', 'public.home.social.mail.description', 'Project inquiries, resume requests, and direct contact.'),
('en', 'public.home.resumePoint.1', 'Full-stack product engineering'),
('en', 'public.home.resumePoint.2', 'Admin workflow design'),
('en', 'public.home.resumePoint.3', 'Performance and SEO hardening'),
('en', 'public.home.resumePoint.4', 'Technical writing systems'),
('en', 'public.home.resumeMeta.basedIn.label', 'Based in'),
('en', 'public.home.resumeMeta.basedIn.value', 'Istanbul / Remote'),
('en', 'public.home.resumeMeta.workingWith.label', 'Working with'),
('en', 'public.home.resumeMeta.workingWith.value', 'Founders, agencies, product teams'),
('en', 'public.home.resumeMeta.delivery.label', 'Delivery'),
('en', 'public.home.resumeMeta.delivery.value', 'Design systems, apps, and content platforms'),
('en', 'public.home.resumeFocusValue', 'product systems, dashboards, publishing'),
('en', 'public.home.availabilityLabel', 'Availability'),
('en', 'public.home.runtimeCommandLabel', 'Runtime command'),
('en', 'public.home.techDescription', 'Core tools I reach for when the product needs sharp routing, typed contracts, and deployment paths that stay boring in production.'),
('en', 'public.projects.emptyBody', 'Published project cards will appear here as soon as the first public case studies are ready.'),
('en', 'public.projects.emptyEyebrow', 'Project registry'),
('en', 'public.projects.emptyTitle', 'No public projects yet.'),
('en', 'public.projects.feedLoading', 'Loading the next set...'),
('en', 'public.projects.feedReady', 'Scroll to load more projects'),
('en', 'public.projects.featuredBadge', 'Featured'),
('en', 'public.projects.heroBody', 'A public registry of shipped interfaces, content systems, and dashboard flows built for fast routes, clear data contracts, and maintainable delivery.'),
('en', 'public.projects.heroEyebrow', 'Selected builds / Public registry'),
('en', 'public.projects.heroTitle', 'Projects That Ship With Sharp Edges.'),
('en', 'public.projects.liveCta', 'Live build'),
('en', 'public.projects.repoCta', 'Source'),
('en', 'public.projects.scrollHint', 'Automatic loading continues as you scroll.'),
('en', 'public.projects.statFeatured', 'Featured'),
('en', 'public.projects.statLive', 'Live links'),
('en', 'public.projects.statTotal', 'Published'),
('en', 'public.projects.techLabel', 'Stack focus'),
('en', 'public.blog.archiveCaption', 'Published notes, postmortems, and deploy logs from the same paper desk.'),
('en', 'public.blog.archiveEyebrow', 'Public logbook'),
('en', 'public.blog.archiveTitle', 'Field Notes From the Edge'),
('en', 'public.blog.authorLabel', 'By'),
('en', 'public.blog.authorFallbackBio', 'Working around edge-native applications and editorial experience.'),
('en', 'public.blog.backToBlog', 'Back to blog'),
('en', 'public.blog.emptyBody', 'Public notes are being edited right now. The editorial pipeline is ready, but no published story is available yet.'),
('en', 'public.blog.emptyTitle', 'Notebook still drying'),
('en', 'public.blog.feedLoading', 'Loading the next set...'),
('en', 'public.blog.feedReady', 'Scroll to load more notes'),
('en', 'public.blog.moreNotesTitle', 'More notes'),
('en', 'public.blog.notebookIndexTitle', 'Notebook index'),
('en', 'public.blog.recentTopicsTitle', 'Recent topics'),
('en', 'public.blog.readTimeSuffix', 'min read'),
('en', 'public.blog.scrollHint', 'Automatic loading continues as you scroll.'),
('en', 'public.blog.updatedLabel', 'Updated'),
('en', 'public.blog.topic.1', 'Cloudflare'),
('en', 'public.blog.topic.2', 'React Router'),
('en', 'public.blog.topic.3', 'D1'),
('en', 'public.blog.topic.4', 'Editorial UX'),
('en', 'public.blog.topic.5', 'Observability'),
('en', 'public.blog.topic.6', 'Deploy Notes'),
('en', 'login.adminBadge', 'Admin'),
('en', 'login.buildLabel', 'Build: v2.4.2-stable'),
('en', 'login.buttonIdle', 'Login_To_Terminal'),
('en', 'login.buttonSubmitting', 'Logging_In...'),
('en', 'login.emailLabel', 'Email'),
('en', 'login.emailPlaceholder', 'ADMIN_USER@INK.DEV'),
('en', 'login.footerSecurity', 'HttpOnly / Secure / SameSite=Lax'),
('en', 'login.heading', 'Access'),
('en', 'login.headingHighlight', 'Admins'),
('en', 'login.headingTail', 'Only'),
('en', 'login.nodeLabel', 'Node: TR-IST-01'),
('en', 'login.passwordLabel', 'Password'),
('en', 'login.returnToSite', 'Return_To_Site'),
('en', 'login.securityDescription', 'Session monitoring active. Unauthorized attempts will be logged.'),
('en', 'login.securityLevel', 'Security Level: Alpha'),
('en', 'login.siteName', 'Paper Enes Ink'),
('en', 'dashboard.layout.navDashboard', 'Dashboard'),
('en', 'dashboard.layout.navPosts', 'Posts'),
('en', 'dashboard.layout.navProjects', 'Projects'),
('en', 'dashboard.layout.navSkills', 'Skills'),
('en', 'dashboard.layout.navUsers', 'Users'),
('en', 'dashboard.layout.navSettings', 'Settings'),
('en', 'dashboard.layout.navStatusLive', 'Live'),
('en', 'dashboard.layout.navStatusLater', 'Later'),
('en', 'dashboard.layout.closeMenuAriaLabel', 'Close navigation menu'),
('en', 'dashboard.layout.closeOverlayAriaLabel', 'Close navigation overlay'),
('en', 'dashboard.layout.logoutAriaLabel', 'Logout current admin session'),
('en', 'dashboard.layout.logoutLabel', 'Logout'),
('en', 'dashboard.layout.menuOpenAriaLabel', 'Open navigation menu'),
('en', 'dashboard.layout.navigationAriaLabel', 'Dashboard'),
('en', 'dashboard.layout.shellTitle', 'Admin Portal'),
('en', 'dashboard.layout.shellVersion', 'V1.0.4-stable'),
('en', 'dashboard.layout.statusDescription', 'Session secured / dashboard shell active'),
('en', 'dashboard.layout.statusTitle', 'System Status: Logged In'),
('en', 'dashboard.layout.roleAccessSuffix', 'access'),
('en', 'dashboard.projects.createActionLabel', 'Create new project'),
('en', 'dashboard.projects.createDescription', 'Create a new project and add it to the dashboard registry.'),
('en', 'dashboard.projects.createTitle', 'Create project'),
('en', 'dashboard.projects.editActionLabel', 'Update project'),
('en', 'dashboard.projects.editDescription', 'Update the existing project record and persist changes on the server.'),
('en', 'dashboard.projects.editTitle', 'Edit project'),
('en', 'dashboard.projects.emptyState', 'No projects yet.'),
('en', 'dashboard.projects.featuredLabel', 'Featured'),
('en', 'dashboard.projects.featuredToggleLabel', 'Featured project'),
('en', 'dashboard.projects.inventoryEyebrow', 'Live inventory'),
('en', 'dashboard.projects.registryTitle', 'Project registry'),
('en', 'dashboard.projects.tableActionsLabel', 'Actions'),
('en', 'dashboard.projects.tableNameLabel', 'Project name'),
('en', 'dashboard.projects.tableStatusLabel', 'Status'),
('en', 'dashboard.projects.tableSummaryLabel', 'Summary'),
('en', 'dashboard.projects.metricTotal', 'Total projects'),
('en', 'dashboard.projects.metricFeatured', 'Featured nodes'),
('en', 'dashboard.projects.metricLive', 'Live links'),
('en', 'dashboard.projects.form.cancelLabel', 'Cancel'),
('en', 'dashboard.projects.form.coverImageUrl.label', 'Cover image URL'),
('en', 'dashboard.projects.form.coverImageUrl.placeholder', 'https://images...'),
('en', 'dashboard.projects.form.description.label', 'Description'),
('en', 'dashboard.projects.form.error.deleteMissingProject', 'The project to delete could not be found.'),
('en', 'dashboard.projects.form.error.updateMissingProject', 'The project to update could not be found.'),
('en', 'dashboard.projects.form.liveUrl.label', 'Live URL'),
('en', 'dashboard.projects.form.liveUrl.placeholder', 'https://project.example'),
('en', 'dashboard.projects.form.repositoryUrl.label', 'Repository URL'),
('en', 'dashboard.projects.form.repositoryUrl.placeholder', 'https://github.com/...'),
('en', 'dashboard.projects.form.slug.label', 'Slug'),
('en', 'dashboard.projects.form.slug.placeholder', 'cyber-store-front'),
('en', 'dashboard.projects.form.sortOrder.label', 'Sort order'),
('en', 'dashboard.projects.form.sortOrder.placeholder', '0'),
('en', 'dashboard.projects.form.status.label', 'Status'),
('en', 'dashboard.projects.form.summary.label', 'Summary'),
('en', 'dashboard.projects.form.summary.placeholder', 'Edge-first commerce frontend for a retro showcase.'),
('en', 'dashboard.projects.form.title.label', 'Project name'),
('en', 'dashboard.projects.form.title.placeholder', 'CYBER_STORE_FRONT'),
('en', 'dashboard.posts.createActionLabel', 'Create new post'),
('en', 'dashboard.posts.createDescription', 'Add a new story to the publishing pipeline and manage its state from the dashboard.'),
('en', 'dashboard.posts.composeEyebrow', 'Draft / Saved locally'),
('en', 'dashboard.posts.createTitle', 'Create post'),
('en', 'dashboard.posts.editActionLabel', 'Update post'),
('en', 'dashboard.posts.editDescription', 'Update the body, publish date, and status of the existing story.'),
('en', 'dashboard.posts.editTitle', 'Edit post'),
('en', 'dashboard.posts.emptyState', 'No posts yet. Add your first story.'),
('en', 'dashboard.posts.inventoryEyebrow', 'Publishing pipeline'),
('en', 'dashboard.posts.publishedLabel', 'Published'),
('en', 'dashboard.posts.registryTitle', 'Post registry'),
('en', 'dashboard.posts.tableActionsLabel', 'Actions'),
('en', 'dashboard.posts.tableNameLabel', 'Post name'),
('en', 'dashboard.posts.tableStatusLabel', 'Status'),
('en', 'dashboard.posts.tableSummaryLabel', 'Summary'),
('en', 'dashboard.posts.metricTotal', 'Total posts'),
('en', 'dashboard.posts.metricPublished', 'Published posts'),
('en', 'dashboard.posts.metricDraft', 'Draft queue'),
('en', 'dashboard.posts.form.backToListLabel', 'Back to posts'),
('en', 'dashboard.posts.form.closeFullscreenLabel', 'Close editor'),
('en', 'dashboard.posts.form.content.label', 'Story body'),
('en', 'dashboard.posts.form.content.placeholder', 'Tell your story...'),
('en', 'dashboard.posts.form.coverImageUrl.label', 'Cover image URL'),
('en', 'dashboard.posts.form.coverImageUrl.placeholder', 'https://cdn.paper-portfolio-ink.dev/posts/edge-cache.webp'),
('en', 'dashboard.posts.form.error.deleteMissingPost', 'The post to delete could not be found.'),
('en', 'dashboard.posts.form.error.missingAuthor', 'Active user could not be resolved. Please sign in again.'),
('en', 'dashboard.posts.form.error.updateMissingPost', 'The post id to update is missing.'),
('en', 'dashboard.posts.form.editor.imagePromptLabel', 'Enter image address'),
('en', 'dashboard.posts.form.editor.linkPromptLabel', 'Enter link address'),
('en', 'dashboard.posts.form.editor.loadingLabel', 'Editor is preparing...'),
('en', 'dashboard.posts.form.editor.urlDefaultValue', 'https://'),
('en', 'dashboard.posts.form.excerpt.label', 'Excerpt'),
('en', 'dashboard.posts.form.excerpt.placeholder', 'Short summary shown on the listing screen.'),
('en', 'dashboard.posts.form.fullscreenTitlePlaceholder', 'Tell your story...'),
('en', 'dashboard.posts.form.heroHelper', 'Keep the writing flow minimal and manage publishing metadata from the side panel.'),
('en', 'dashboard.posts.form.publishedAt.label', 'Published on'),
('en', 'dashboard.posts.form.slug.label', 'Slug'),
('en', 'dashboard.posts.form.slug.placeholder', 'edge-cache-rollout'),
('en', 'dashboard.posts.form.status.label', 'Status'),
('en', 'dashboard.posts.form.title.label', 'Post title'),
('en', 'dashboard.posts.form.title.placeholder', 'Edge Cache Rollout Notes'),
('en', 'dashboard.posts.composeTitle', 'Compose'),
('en', 'dashboard.posts.setupTitle', 'Story setup'),
('en', 'dashboard.posts.flowTitle', 'Editor flow'),
('en', 'dashboard.posts.createdLabel', 'Created'),
('en', 'dashboard.posts.updatedLabel', 'Updated'),
('en', 'dashboard.posts.publishedAtLabel', 'Published'),
('en', 'dashboard.skills.actionBlockedTitle', 'Action blocked'),
('en', 'dashboard.skills.createActionLabel', 'Create skill'),
('en', 'dashboard.skills.createDescription', 'Add a portfolio skill entry that can later be reused across public stack surfaces.'),
('en', 'dashboard.skills.createTitle', 'Create skill'),
('en', 'dashboard.skills.currentRoleLabel', 'Current role'),
('en', 'dashboard.skills.editActionLabel', 'Update skill'),
('en', 'dashboard.skills.editDescription', 'Refine icon, summary, and ordering metadata for an existing skill entry.'),
('en', 'dashboard.skills.editTitle', 'Edit skill'),
('en', 'dashboard.skills.emptyState', 'No skills registered yet.'),
('en', 'dashboard.skills.inventoryEyebrow', 'Portfolio taxonomy'),
('en', 'dashboard.skills.registryTitle', 'Skills registry'),
('en', 'dashboard.skills.restrictedDescription', 'You do not have permission to access this flow.'),
('en', 'dashboard.skills.restrictedTitle', 'Restricted flow'),
('en', 'dashboard.skills.metricTotal', 'Total skills'),
('en', 'dashboard.skills.tableActionsLabel', 'Actions'),
('en', 'dashboard.skills.tableCreatedLabel', 'Created'),
('en', 'dashboard.skills.tableIconLabel', 'Icon'),
('en', 'dashboard.skills.tableNameLabel', 'Skill'),
('en', 'dashboard.skills.tableSortLabel', 'Sort'),
('en', 'dashboard.skills.tableSlugLabel', 'Key'),
('en', 'dashboard.skills.tableSummaryLabel', 'Summary'),
('en', 'dashboard.skills.generatedKeyLabel', 'Generated key'),
('en', 'dashboard.skills.generatedKeyPlaceholder', 'Waiting for a valid skill name'),
('en', 'dashboard.skills.selectedIconLabel', 'Selected icon'),
('en', 'dashboard.skills.form.cancelLabel', 'Cancel'),
('en', 'dashboard.skills.form.error.createDuplicateSkill', 'This skill is already registered.'),
('en', 'dashboard.skills.form.error.deleteMissingSkill', 'The skill to delete could not be found.'),
('en', 'dashboard.skills.form.error.forbidden', 'You do not have permission to access this flow.'),
('en', 'dashboard.skills.form.error.updateDuplicateSkill', 'This skill is already used by another record.'),
('en', 'dashboard.skills.form.error.updateMissingSkill', 'The skill to update could not be found.'),
('en', 'dashboard.skills.form.iconKey.label', 'Icon'),
('en', 'dashboard.skills.form.name.label', 'Skill name'),
('en', 'dashboard.skills.form.name.placeholder', 'Cloudflare D1'),
('en', 'dashboard.skills.form.sortOrder.label', 'Sort order'),
('en', 'dashboard.skills.form.sortOrder.placeholder', '0'),
('en', 'dashboard.skills.form.summary.label', 'Summary'),
('en', 'dashboard.skills.form.summary.placeholder', 'Edge database workflows for globally distributed product systems.'),
('en', 'dashboard.users.actionBlockedTitle', 'Action blocked'),
('en', 'dashboard.users.createActionLabel', 'Create new user'),
('en', 'dashboard.users.createDescription', 'Create a credential-backed dashboard user with scoped role access.'),
('en', 'dashboard.users.createTitle', 'Create user'),
('en', 'dashboard.users.currentRoleLabel', 'Current role'),
('en', 'dashboard.users.editActionLabel', 'Update user'),
('en', 'dashboard.users.editDescription', 'Update identity fields, role access, or rotate the credential password.'),
('en', 'dashboard.users.editTitle', 'Edit user'),
('en', 'dashboard.users.emptyState', 'No dashboard users provisioned yet.'),
('en', 'dashboard.users.inventoryEyebrow', 'Access control'),
('en', 'dashboard.users.registryTitle', 'User registry'),
('en', 'dashboard.users.restrictedDescription', 'You do not have permission to access this flow.'),
('en', 'dashboard.users.restrictedTitle', 'Restricted flow'),
('en', 'dashboard.users.selfLabel', 'You'),
('en', 'dashboard.users.metricTotal', 'Total users'),
('en', 'dashboard.users.metricAdmin', 'Admin seats'),
('en', 'dashboard.users.metricAuthor', 'Author seats'),
('en', 'dashboard.users.tableActionsLabel', 'Actions'),
('en', 'dashboard.users.tableIdentityLabel', 'Identity'),
('en', 'dashboard.users.tableMetaLabel', 'Meta'),
('en', 'dashboard.users.tableRoleLabel', 'Role'),
('en', 'dashboard.users.metaCreatedPrefix', 'Created'),
('en', 'dashboard.users.metaUpdatedPrefix', 'Updated'),
('en', 'dashboard.users.metaAvatarBound', 'Avatar bound'),
('en', 'dashboard.users.metaNoAvatar', 'No avatar'),
('en', 'dashboard.users.metaSessionEnabled', 'Session enabled'),
('en', 'dashboard.users.metaSessionDisabled', 'Session disabled'),
('en', 'dashboard.shared.dismiss', 'Dismiss'),
('en', 'dashboard.users.form.avatarUrl.label', 'Avatar URL'),
('en', 'dashboard.users.form.avatarUrl.placeholder', 'https://images.paper-portfolio-ink.dev/avatar.webp'),
('en', 'dashboard.users.form.bio.label', 'Bio'),
('en', 'dashboard.users.form.bio.placeholder', 'Short operational context for the dashboard team.'),
('en', 'dashboard.users.form.cancelLabel', 'Cancel'),
('en', 'dashboard.users.form.displayName.label', 'Display name'),
('en', 'dashboard.users.form.displayName.placeholder', 'Ayla Author'),
('en', 'dashboard.users.form.email.label', 'Email'),
('en', 'dashboard.users.form.email.placeholder', 'author@paper-portfolio-ink.dev'),
('en', 'dashboard.users.form.error.createDuplicateEmail', 'This email address is already in use.'),
('en', 'dashboard.users.form.error.deactivateMissingUser', 'The user to deactivate could not be found.'),
('en', 'dashboard.users.form.error.forbidden', 'You do not have permission to access this flow.'),
('en', 'dashboard.users.form.error.lastActiveAdminDeactivate', 'The last active admin account cannot be deactivated.'),
('en', 'dashboard.users.form.error.lastActiveAdminDemotion', 'The last active admin account cannot be demoted to author.'),
('en', 'dashboard.users.form.error.lastActiveAdminDelete', 'The last active admin account cannot be removed.'),
('en', 'dashboard.users.form.error.updateDuplicateEmail', 'This email address belongs to another user.'),
('en', 'dashboard.users.form.error.updateMissingUser', 'The user to update could not be found.'),
('en', 'dashboard.users.form.password.editHint', 'Leave empty to keep the current password.'),
('en', 'dashboard.users.form.password.label', 'Password'),
('en', 'dashboard.users.form.password.placeholder', 'PaperInk1234!'),
('en', 'dashboard.users.form.role.label', 'Role'),
('en', 'dashboard.users.form.statusLabel', 'Keep account active'),
('en', 'dashboard.overview.stat.totalPosts.label', 'Total posts'),
('en', 'dashboard.overview.stat.totalViews.label', 'Total views'),
('en', 'dashboard.overview.stat.projectSuccess.label', 'Project success'),
('en', 'dashboard.overview.stat.serverLoad.label', 'Server load'),
('en', 'dashboard.overview.stat.stable', 'Stable'),
('en', 'dashboard.overview.stat.optimal', 'Optimal'),
('en', 'dashboard.overview.post.1.category', 'Design'),
('en', 'dashboard.overview.post.1.status', 'Published'),
('en', 'dashboard.overview.post.1.title', 'Neo-Brutalism in UI Design'),
('en', 'dashboard.overview.post.2.category', 'Tech'),
('en', 'dashboard.overview.post.2.status', 'Draft'),
('en', 'dashboard.overview.post.2.title', 'The Future of Web Development'),
('en', 'dashboard.overview.post.3.category', 'Tutorial'),
('en', 'dashboard.overview.post.3.status', 'Published'),
('en', 'dashboard.overview.post.3.title', 'Scaling CSS for Large Projects'),
('en', 'dashboard.overview.log.1.time', '2 hours ago'),
('en', 'dashboard.overview.log.1.title', 'Updated blog post: Neo-Brutalism in UI Design'),
('en', 'dashboard.overview.log.2.time', 'Yesterday'),
('en', 'dashboard.overview.log.2.title', 'New project added: Edge Commerce'),
('en', 'dashboard.overview.log.3.time', '3 days ago'),
('en', 'dashboard.overview.log.3.title', 'System configuration changed'),
('en', 'model.projectStatus.draft', 'Draft'),
('en', 'model.projectStatus.published', 'Published'),
('en', 'model.projectStatus.archived', 'Archived'),
('en', 'model.postStatus.draft', 'Draft'),
('en', 'model.postStatus.published', 'Published'),
('en', 'model.postStatus.archived', 'Archived'),
('en', 'model.userRole.admin', 'Admin'),
('en', 'model.userRole.author', 'Author'),
('en', 'skillIcon.cloud.label', 'Cloud'),
('en', 'skillIcon.cloud.description', 'Distributed systems, edge services, and platform delivery.'),
('en', 'skillIcon.database.label', 'Database'),
('en', 'skillIcon.database.description', 'Database design, query workflows, and storage layers.'),
('en', 'skillIcon.code.label', 'Code'),
('en', 'skillIcon.code.description', 'Typed frontend and backend implementation details.'),
('en', 'skillIcon.workflow.label', 'Workflow'),
('en', 'skillIcon.workflow.description', 'Architecture stitching, orchestration, and flow modeling.'),
('en', 'skillIcon.shield.label', 'Security'),
('en', 'skillIcon.shield.description', 'System hardening, trust boundaries, and access control.'),
('en', 'skillIcon.rocket.label', 'Launch'),
('en', 'skillIcon.rocket.description', 'Deployment pipelines, launch readiness, and product momentum.'),
('en', 'skillIcon.layers.label', 'Interface'),
('en', 'skillIcon.layers.description', 'Composable UI systems and reusable surface primitives.'),
('en', 'skillIcon.pen.label', 'Editorial'),
('en', 'skillIcon.pen.description', 'Content systems, editorial tooling, and writing workflows.'),
('en', 'skillIcon.blocks.label', 'Modules'),
('en', 'skillIcon.blocks.description', 'Infrastructure modules, platform parts, and shared building blocks.'),
('en', 'skillIcon.wrench.label', 'Operations'),
('en', 'skillIcon.wrench.description', 'Operations, runtime maintenance, and practical engineering work.'),
('en', 'skillIcon.globe.label', 'Web'),
('en', 'skillIcon.globe.description', 'Public-facing systems, reach, and globally accessible experiences.'),
('en', 'validation.project.title.min', 'Project title must be at least 3 characters.'),
('en', 'validation.project.title.max', 'Project title can be at most 80 characters.'),
('en', 'validation.project.slug.pattern', 'Slug may only contain lowercase letters, numbers, and hyphens.'),
('en', 'validation.project.slug.min', 'Slug must be at least 3 characters.'),
('en', 'validation.project.summary.min', 'Project summary must be at least 12 characters.'),
('en', 'validation.project.summary.max', 'Project summary can be at most 180 characters.'),
('en', 'validation.project.description.max', 'Description can be at most 3000 characters.'),
('en', 'validation.project.repositoryUrl', 'Enter a valid repository URL.'),
('en', 'validation.project.liveUrl', 'Enter a valid live URL.'),
('en', 'validation.project.coverImageUrl', 'Enter a valid cover image URL.'),
('en', 'validation.project.status', 'Select a valid publishing status.'),
('en', 'validation.project.sortOrder.int', 'Sort order must be an integer.'),
('en', 'validation.project.sortOrder.min', 'Sort order must be greater than or equal to 0.'),
('en', 'validation.post.title.min', 'Post title must be at least 3 characters.'),
('en', 'validation.post.title.max', 'Post title can be at most 120 characters.'),
('en', 'validation.post.slug.pattern', 'Slug may only contain lowercase letters, numbers, and hyphens.'),
('en', 'validation.post.slug.min', 'Slug must be at least 3 characters.'),
('en', 'validation.post.excerpt.min', 'Excerpt must be at least 12 characters.'),
('en', 'validation.post.excerpt.max', 'Excerpt can be at most 240 characters.'),
('en', 'validation.post.content.min', 'Post body must be at least 20 characters.'),
('en', 'validation.post.content.max', 'Post body can be at most 100000 characters.'),
('en', 'validation.post.coverImageUrl', 'Enter a valid cover image URL.'),
('en', 'validation.post.status', 'Select a valid publishing status.'),
('en', 'validation.skill.icon', 'Select a valid icon.'),
('en', 'validation.skill.name.min', 'Skill name must be at least 2 characters.'),
('en', 'validation.skill.name.max', 'Skill name can be at most 48 characters.'),
('en', 'validation.skill.name.slug', 'Skill name did not generate a valid key.'),
('en', 'validation.skill.summary.min', 'Skill summary must be at least 12 characters.'),
('en', 'validation.skill.summary.max', 'Skill summary can be at most 180 characters.'),
('en', 'validation.skill.sortOrder.int', 'Sort order must be an integer.'),
('en', 'validation.skill.sortOrder.min', 'Sort order must be greater than or equal to 0.'),
('en', 'validation.user.avatarUrl', 'Enter a valid avatar URL.'),
('en', 'validation.user.bio.max', 'Bio can be at most 500 characters.'),
('en', 'validation.user.displayName.min', 'Display name must be at least 2 characters.'),
('en', 'validation.user.displayName.max', 'Display name can be at most 80 characters.'),
('en', 'validation.user.email', 'Enter a valid email address.'),
('en', 'validation.user.password.max', 'Password can be at most 128 characters.'),
('en', 'validation.user.role', 'Select a valid user role.'),
('en', 'validation.user.password.createMin', 'Password must be at least 8 characters.'),
('en', 'validation.user.password.updateMin', 'If the password changes, it must be at least 8 characters.'),
('en', 'validation.login.email', 'Enter a valid email address.'),
('en', 'validation.login.password.min', 'Password must be at least 8 characters.'),
('en', 'validation.login.password.max', 'Password can be at most 128 characters.'),
('en', 'validation.login.invalidCredentials', 'Email or password is incorrect.'),
('en', 'validation.login.unavailable', 'Login could not be completed right now.'),
('en', 'validation.slug.taken', 'This slug is already in use. Choose another slug.'),
('en', 'aria.publicBlog.cover', 'cover image'),
('en', 'aria.dashboardModal.closeOverlay', 'Close dashboard modal overlay'),
('en', 'aria.dashboardModal.close', 'Close dashboard modal'),
('en', 'aria.projects.edit', 'Edit'),
('en', 'aria.projects.delete', 'Delete'),
('en', 'aria.users.edit', 'Edit'),
('en', 'aria.users.delete', 'Delete')
ON CONFLICT(`locale`, `key`) DO UPDATE SET
`value` = excluded.`value`,
`updated_at` = (unixepoch() * 1000);
