INSERT INTO `translations` (`locale`, `key`, `value`)
VALUES
  ('tr', 'public.layout.navMobileAriaLabel', 'Mobil public navigasyon'),
  ('tr', 'public.layout.navPrimaryAriaLabel', 'Public navigasyon'),
  ('tr', 'public.blog.emptyContent', 'Yazi govdesi yakinda guncellenecek.'),
  ('tr', 'dashboard.projects.tableLiveFlag', 'Canli'),
  ('tr', 'dashboard.projects.tableRepositoryFlag', 'Repo'),
  ('tr', 'dashboard.projects.tableSortPrefix', 'Sira'),
  ('tr', 'dashboard.posts.form.editor.toolbar.blockquote', 'Alinti'),
  ('tr', 'dashboard.posts.form.editor.toolbar.bold', 'Kalin'),
  ('tr', 'dashboard.posts.form.editor.toolbar.bulletList', 'Madde listesi'),
  ('tr', 'dashboard.posts.form.editor.toolbar.codeBlock', 'Kod alani'),
  ('tr', 'dashboard.posts.form.editor.toolbar.heading1', 'Baslik 1'),
  ('tr', 'dashboard.posts.form.editor.toolbar.heading2', 'Baslik 2'),
  ('tr', 'dashboard.posts.form.editor.toolbar.heading3', 'Baslik 3'),
  ('tr', 'dashboard.posts.form.editor.toolbar.horizontalRule', 'Yatay cizgi'),
  ('tr', 'dashboard.posts.form.editor.toolbar.image', 'Gorsel ekle'),
  ('tr', 'dashboard.posts.form.editor.toolbar.italic', 'Italik'),
  ('tr', 'dashboard.posts.form.editor.toolbar.orderedList', 'Sirali liste'),
  ('tr', 'dashboard.posts.form.editor.toolbar.redo', 'Yinele'),
  ('tr', 'dashboard.posts.form.editor.toolbar.setLink', 'Baglanti ekle'),
  ('tr', 'dashboard.posts.form.editor.toolbar.undo', 'Geri al'),
  ('tr', 'dashboard.posts.form.editor.toolbar.underline', 'Alti cizili'),
  ('tr', 'dashboard.posts.form.editor.toolbar.unsetLink', 'Baglantiyi kaldir'),
  ('tr', 'dashboard.modal.eyebrow', 'Project Forge'),
  ('en', 'public.layout.navMobileAriaLabel', 'Mobile public navigation'),
  ('en', 'public.layout.navPrimaryAriaLabel', 'Public navigation'),
  ('en', 'public.blog.emptyContent', 'The post body will be updated soon.'),
  ('en', 'dashboard.projects.tableLiveFlag', 'Live'),
  ('en', 'dashboard.projects.tableRepositoryFlag', 'Repo'),
  ('en', 'dashboard.projects.tableSortPrefix', 'Sort'),
  ('en', 'dashboard.posts.form.editor.toolbar.blockquote', 'Blockquote'),
  ('en', 'dashboard.posts.form.editor.toolbar.bold', 'Bold'),
  ('en', 'dashboard.posts.form.editor.toolbar.bulletList', 'Bullet list'),
  ('en', 'dashboard.posts.form.editor.toolbar.codeBlock', 'Code block'),
  ('en', 'dashboard.posts.form.editor.toolbar.heading1', 'Heading 1'),
  ('en', 'dashboard.posts.form.editor.toolbar.heading2', 'Heading 2'),
  ('en', 'dashboard.posts.form.editor.toolbar.heading3', 'Heading 3'),
  ('en', 'dashboard.posts.form.editor.toolbar.horizontalRule', 'Horizontal rule'),
  ('en', 'dashboard.posts.form.editor.toolbar.image', 'Insert image'),
  ('en', 'dashboard.posts.form.editor.toolbar.italic', 'Italic'),
  ('en', 'dashboard.posts.form.editor.toolbar.orderedList', 'Ordered list'),
  ('en', 'dashboard.posts.form.editor.toolbar.redo', 'Redo'),
  ('en', 'dashboard.posts.form.editor.toolbar.setLink', 'Set link'),
  ('en', 'dashboard.posts.form.editor.toolbar.undo', 'Undo'),
  ('en', 'dashboard.posts.form.editor.toolbar.underline', 'Underline'),
  ('en', 'dashboard.posts.form.editor.toolbar.unsetLink', 'Unset link'),
  ('en', 'dashboard.modal.eyebrow', 'Project Forge')
ON CONFLICT(`locale`, `key`) DO UPDATE SET
  `value` = excluded.`value`,
  `updated_at` = (unixepoch() * 1000);
