INSERT INTO `translations` (`locale`, `key`, `value`)
VALUES
  ('tr', 'dashboard.layout.navResources', 'Kaynaklar'),
  ('tr', 'dashboard.resources.actionBlockedTitle', 'Aksiyon engellendi'),
  ('tr', 'dashboard.resources.cacheDescription', 'Locale ve translations kayitlari ayni cache invalidation hatti ile temizlenir. Locale degisirse locale listesi ve ilgili mesaj cache''leri birlikte bosaltilir.'),
  ('tr', 'dashboard.resources.cacheEyebrow', 'Cache odakli ayarlar'),
  ('tr', 'dashboard.resources.createLocaleActionLabel', 'Locale ekle'),
  ('tr', 'dashboard.resources.createLocaleDescription', 'Yeni bir locale kaydi ekle; aktif/default durumu ve sira bilgisi cache ile uyumlu sekilde kaydedilsin.'),
  ('tr', 'dashboard.resources.createLocaleTitle', 'Locale olustur'),
  ('tr', 'dashboard.resources.createTranslationActionLabel', 'Translation ekle'),
  ('tr', 'dashboard.resources.createTranslationDescription', 'Secili locale icin yeni bir mesaj anahtari ekle ve request-time cache''i aninda guncelle.'),
  ('tr', 'dashboard.resources.createTranslationTitle', 'Translation olustur'),
  ('tr', 'dashboard.resources.currentRoleLabel', 'Mevcut rol'),
  ('tr', 'dashboard.resources.defaultBadge', 'Varsayilan'),
  ('tr', 'dashboard.resources.editLocaleActionLabel', 'Locale guncelle'),
  ('tr', 'dashboard.resources.editLocaleDescription', 'Locale kodu, etiketi ve aktif/default durumu tek modal yuzeyinden guncellenir.'),
  ('tr', 'dashboard.resources.editLocaleTitle', 'Locale duzenle'),
  ('tr', 'dashboard.resources.editTranslationActionLabel', 'Translation guncelle'),
  ('tr', 'dashboard.resources.editTranslationDescription', 'Mesaj anahtari, locale baglantisi ve value icerigini duzenle.'),
  ('tr', 'dashboard.resources.editTranslationTitle', 'Translation duzenle'),
  ('tr', 'dashboard.resources.emptyLocales', 'Henuz locale kaydi yok.'),
  ('tr', 'dashboard.resources.emptyTranslations', 'Bu locale icin henuz translation kaydi yok.'),
  ('tr', 'dashboard.resources.localeFilterTitle', 'Translation locale filtresi'),
  ('tr', 'dashboard.resources.localeInventoryEyebrow', 'Locale registry'),
  ('tr', 'dashboard.resources.localeTabLabel', 'Locales'),
  ('tr', 'dashboard.resources.metricActiveLocales', 'Aktif locale'),
  ('tr', 'dashboard.resources.metricSelectedLocaleTranslations', 'Secili locale mesaji'),
  ('tr', 'dashboard.resources.metricTotalLocales', 'Toplam locale'),
  ('tr', 'dashboard.resources.metricTotalTranslations', 'Toplam translation'),
  ('tr', 'dashboard.resources.registryTitle', 'Resource ayarlari'),
  ('tr', 'dashboard.resources.restrictedDescription', 'Bu flow icin erisim yetkiniz yoktur.'),
  ('tr', 'dashboard.resources.restrictedTitle', 'Kisitli akis'),
  ('tr', 'dashboard.resources.clearSearchLabel', 'Temizle'),
  ('tr', 'dashboard.resources.searchEmptyState', 'Bu arama ile eslesen translation kaydi bulunamadi.'),
  ('tr', 'dashboard.resources.searchTitle', 'Translation arama'),
  ('tr', 'dashboard.resources.tabDescription', 'Locale registry ve translations tablolarini ayni settings yuzeyinde yonet.'),
  ('tr', 'dashboard.resources.tableActionsLabel', 'Aksiyonlar'),
  ('tr', 'dashboard.resources.tableCreatedPrefix', 'Olusturuldu'),
  ('tr', 'dashboard.resources.tableLocaleCodeLabel', 'Locale'),
  ('tr', 'dashboard.resources.tableLocaleMetaLabel', 'Meta'),
  ('tr', 'dashboard.resources.tableLocaleStatusLabel', 'Durum'),
  ('tr', 'dashboard.resources.tableSortPrefix', 'Sira'),
  ('tr', 'dashboard.resources.tableTranslationsPrefix', 'Mesaj'),
  ('tr', 'dashboard.resources.tableTranslationKeyLabel', 'Anahtar'),
  ('tr', 'dashboard.resources.tableTranslationUpdatedLabel', 'Zaman'),
  ('tr', 'dashboard.resources.tableTranslationValueLabel', 'Deger'),
  ('tr', 'dashboard.resources.tableUpdatedPrefix', 'Guncellendi'),
  ('tr', 'dashboard.resources.translationInventoryEyebrow', 'Translation registry'),
  ('tr', 'dashboard.resources.translationTabLabel', 'Translations'),
  ('tr', 'dashboard.resources.form.cancelLabel', 'Iptal'),
  ('tr', 'dashboard.resources.form.error.createLocaleDuplicateCode', 'Bu locale kodu zaten kayitli.'),
  ('tr', 'dashboard.resources.form.error.createTranslationDuplicateKey', 'Bu translation anahtari secili locale icin zaten var.'),
  ('tr', 'dashboard.resources.form.error.deleteLocaleMissing', 'Silinecek locale bulunamadi.'),
  ('tr', 'dashboard.resources.form.error.deleteLocaleRestricted', 'Son aktif/default locale kaldirilamaz.'),
  ('tr', 'dashboard.resources.form.error.deleteTranslationMissing', 'Silinecek translation bulunamadi.'),
  ('tr', 'dashboard.resources.form.error.forbidden', 'Bu flow icin erisim yetkiniz yoktur.'),
  ('tr', 'dashboard.resources.form.error.localeMissing', 'Guncellenecek locale kaydi bulunamadi.'),
  ('tr', 'dashboard.resources.form.error.translationLocaleMissing', 'Translation icin gecerli bir locale sec.'),
  ('tr', 'dashboard.resources.form.error.translationMissing', 'Guncellenecek translation kaydi bulunamadi.'),
  ('tr', 'dashboard.resources.form.error.updateLocaleDuplicateCode', 'Bu locale kodu baska bir kayitta zaten kullaniliyor.'),
  ('tr', 'dashboard.resources.form.error.updateLocaleMissing', 'Guncellenecek locale bulunamadi.'),
  ('tr', 'dashboard.resources.form.error.updateTranslationDuplicateKey', 'Bu translation anahtari baska bir kayitta zaten kullaniliyor.'),
  ('tr', 'dashboard.resources.form.error.updateTranslationMissing', 'Guncellenecek translation bulunamadi.'),
  ('tr', 'dashboard.resources.form.locale.activeLabel', 'Aktiflik'),
  ('tr', 'dashboard.resources.form.locale.code.label', 'Locale kodu'),
  ('tr', 'dashboard.resources.form.locale.code.placeholder', 'de'),
  ('tr', 'dashboard.resources.form.locale.defaultLabel', 'Varsayilan locale'),
  ('tr', 'dashboard.resources.form.locale.defaultNo', 'Hayir'),
  ('tr', 'dashboard.resources.form.locale.defaultYes', 'Evet'),
  ('tr', 'dashboard.resources.form.locale.label.label', 'Etiket'),
  ('tr', 'dashboard.resources.form.locale.label.placeholder', 'DE'),
  ('tr', 'dashboard.resources.form.locale.sortOrder.label', 'Siralama'),
  ('tr', 'dashboard.resources.form.locale.sortOrder.placeholder', '2'),
  ('tr', 'dashboard.resources.form.translation.key.label', 'Mesaj anahtari'),
  ('tr', 'dashboard.resources.form.translation.key.placeholder', 'dashboard.layout.navDashboard'),
  ('tr', 'dashboard.resources.form.translation.locale.label', 'Locale'),
  ('tr', 'dashboard.resources.form.translation.search.label', 'Ara'),
  ('tr', 'dashboard.resources.form.translation.search.placeholder', 'Key veya value ile ara'),
  ('tr', 'dashboard.resources.form.translation.value.label', 'Deger'),
  ('tr', 'dashboard.resources.form.translation.value.placeholder', 'Dashboard ana metni buraya yazilir.'),
  ('tr', 'validation.resource.locale.code', 'Gecerli bir locale kodu gir.'),
  ('tr', 'validation.resource.locale.label.min', 'Locale etiketi en az 2 karakter olmali.'),
  ('tr', 'validation.resource.locale.label.max', 'Locale etiketi en fazla 48 karakter olabilir.'),
  ('tr', 'validation.resource.locale.sortOrder.int', 'Siralama tam sayi olmali.'),
  ('tr', 'validation.resource.locale.sortOrder.min', 'Siralama degeri 0 veya daha buyuk olmali.'),
  ('tr', 'validation.resource.locale.defaultActive', 'Varsayilan locale pasif olamaz.'),
  ('tr', 'validation.resource.translation.key.min', 'Translation anahtari en az 2 karakter olmali.'),
  ('tr', 'validation.resource.translation.key.max', 'Translation anahtari en fazla 140 karakter olabilir.'),
  ('tr', 'validation.resource.translation.key.pattern', 'Translation anahtari yalnizca harf, rakam, nokta, tire ve alt cizgi icerebilir.'),
  ('tr', 'validation.resource.translation.locale', 'Gecerli bir locale sec.'),
  ('tr', 'validation.resource.translation.value.min', 'Translation degeri bos birakilamaz.'),
  ('tr', 'validation.resource.translation.value.max', 'Translation degeri en fazla 4000 karakter olabilir.'),
  ('en', 'dashboard.layout.navResources', 'Resources'),
  ('en', 'dashboard.resources.actionBlockedTitle', 'Action blocked'),
  ('en', 'dashboard.resources.cacheDescription', 'Locale and translation records share the same invalidation path. When a locale changes, both the locale list and related message caches are purged together.'),
  ('en', 'dashboard.resources.cacheEyebrow', 'Cache-first settings'),
  ('en', 'dashboard.resources.createLocaleActionLabel', 'Create locale'),
  ('en', 'dashboard.resources.createLocaleDescription', 'Add a new locale record with active/default state and ordering metadata that stays in sync with the runtime cache.'),
  ('en', 'dashboard.resources.createLocaleTitle', 'Create locale'),
  ('en', 'dashboard.resources.createTranslationActionLabel', 'Create translation'),
  ('en', 'dashboard.resources.createTranslationDescription', 'Add a new message key for the selected locale and refresh the request-time cache immediately.'),
  ('en', 'dashboard.resources.createTranslationTitle', 'Create translation'),
  ('en', 'dashboard.resources.currentRoleLabel', 'Current role'),
  ('en', 'dashboard.resources.defaultBadge', 'Default'),
  ('en', 'dashboard.resources.editLocaleActionLabel', 'Update locale'),
  ('en', 'dashboard.resources.editLocaleDescription', 'Update locale code, label, and active/default state from a single modal surface.'),
  ('en', 'dashboard.resources.editLocaleTitle', 'Edit locale'),
  ('en', 'dashboard.resources.editTranslationActionLabel', 'Update translation'),
  ('en', 'dashboard.resources.editTranslationDescription', 'Update the message key, locale binding, and value content.'),
  ('en', 'dashboard.resources.editTranslationTitle', 'Edit translation'),
  ('en', 'dashboard.resources.emptyLocales', 'No locales registered yet.'),
  ('en', 'dashboard.resources.emptyTranslations', 'No translations have been registered for this locale yet.'),
  ('en', 'dashboard.resources.localeFilterTitle', 'Translation locale filter'),
  ('en', 'dashboard.resources.localeInventoryEyebrow', 'Locale registry'),
  ('en', 'dashboard.resources.localeTabLabel', 'Locales'),
  ('en', 'dashboard.resources.metricActiveLocales', 'Active locales'),
  ('en', 'dashboard.resources.metricSelectedLocaleTranslations', 'Selected locale messages'),
  ('en', 'dashboard.resources.metricTotalLocales', 'Total locales'),
  ('en', 'dashboard.resources.metricTotalTranslations', 'Total translations'),
  ('en', 'dashboard.resources.registryTitle', 'Resource settings'),
  ('en', 'dashboard.resources.restrictedDescription', 'You do not have permission to access this flow.'),
  ('en', 'dashboard.resources.restrictedTitle', 'Restricted flow'),
  ('en', 'dashboard.resources.clearSearchLabel', 'Clear'),
  ('en', 'dashboard.resources.searchEmptyState', 'No translation record matched this search.'),
  ('en', 'dashboard.resources.searchTitle', 'Translation search'),
  ('en', 'dashboard.resources.tabDescription', 'Manage locale registry and translation tables from the same settings surface.'),
  ('en', 'dashboard.resources.tableActionsLabel', 'Actions'),
  ('en', 'dashboard.resources.tableCreatedPrefix', 'Created'),
  ('en', 'dashboard.resources.tableLocaleCodeLabel', 'Locale'),
  ('en', 'dashboard.resources.tableLocaleMetaLabel', 'Meta'),
  ('en', 'dashboard.resources.tableLocaleStatusLabel', 'Status'),
  ('en', 'dashboard.resources.tableSortPrefix', 'Sort'),
  ('en', 'dashboard.resources.tableTranslationsPrefix', 'Messages'),
  ('en', 'dashboard.resources.tableTranslationKeyLabel', 'Key'),
  ('en', 'dashboard.resources.tableTranslationUpdatedLabel', 'Timing'),
  ('en', 'dashboard.resources.tableTranslationValueLabel', 'Value'),
  ('en', 'dashboard.resources.tableUpdatedPrefix', 'Updated'),
  ('en', 'dashboard.resources.translationInventoryEyebrow', 'Translation registry'),
  ('en', 'dashboard.resources.translationTabLabel', 'Translations'),
  ('en', 'dashboard.resources.form.cancelLabel', 'Cancel'),
  ('en', 'dashboard.resources.form.error.createLocaleDuplicateCode', 'This locale code is already registered.'),
  ('en', 'dashboard.resources.form.error.createTranslationDuplicateKey', 'This translation key already exists for the selected locale.'),
  ('en', 'dashboard.resources.form.error.deleteLocaleMissing', 'The locale to delete could not be found.'),
  ('en', 'dashboard.resources.form.error.deleteLocaleRestricted', 'The last active/default locale cannot be removed.'),
  ('en', 'dashboard.resources.form.error.deleteTranslationMissing', 'The translation to delete could not be found.'),
  ('en', 'dashboard.resources.form.error.forbidden', 'You do not have permission to access this flow.'),
  ('en', 'dashboard.resources.form.error.localeMissing', 'The locale record to update could not be found.'),
  ('en', 'dashboard.resources.form.error.translationLocaleMissing', 'Select a valid locale for the translation.'),
  ('en', 'dashboard.resources.form.error.translationMissing', 'The translation record to update could not be found.'),
  ('en', 'dashboard.resources.form.error.updateLocaleDuplicateCode', 'This locale code is already used by another record.'),
  ('en', 'dashboard.resources.form.error.updateLocaleMissing', 'The locale to update could not be found.'),
  ('en', 'dashboard.resources.form.error.updateTranslationDuplicateKey', 'This translation key is already used by another record.'),
  ('en', 'dashboard.resources.form.error.updateTranslationMissing', 'The translation to update could not be found.'),
  ('en', 'dashboard.resources.form.locale.activeLabel', 'Active state'),
  ('en', 'dashboard.resources.form.locale.code.label', 'Locale code'),
  ('en', 'dashboard.resources.form.locale.code.placeholder', 'de'),
  ('en', 'dashboard.resources.form.locale.defaultLabel', 'Default locale'),
  ('en', 'dashboard.resources.form.locale.defaultNo', 'No'),
  ('en', 'dashboard.resources.form.locale.defaultYes', 'Yes'),
  ('en', 'dashboard.resources.form.locale.label.label', 'Label'),
  ('en', 'dashboard.resources.form.locale.label.placeholder', 'DE'),
  ('en', 'dashboard.resources.form.locale.sortOrder.label', 'Sort order'),
  ('en', 'dashboard.resources.form.locale.sortOrder.placeholder', '2'),
  ('en', 'dashboard.resources.form.translation.key.label', 'Message key'),
  ('en', 'dashboard.resources.form.translation.key.placeholder', 'dashboard.layout.navDashboard'),
  ('en', 'dashboard.resources.form.translation.locale.label', 'Locale'),
  ('en', 'dashboard.resources.form.translation.search.label', 'Search'),
  ('en', 'dashboard.resources.form.translation.search.placeholder', 'Search by key or value'),
  ('en', 'dashboard.resources.form.translation.value.label', 'Value'),
  ('en', 'dashboard.resources.form.translation.value.placeholder', 'Write the dashboard copy here.'),
  ('en', 'validation.resource.locale.code', 'Enter a valid locale code.'),
  ('en', 'validation.resource.locale.label.min', 'Locale label must be at least 2 characters.'),
  ('en', 'validation.resource.locale.label.max', 'Locale label can be at most 48 characters.'),
  ('en', 'validation.resource.locale.sortOrder.int', 'Sort order must be an integer.'),
  ('en', 'validation.resource.locale.sortOrder.min', 'Sort order must be greater than or equal to 0.'),
  ('en', 'validation.resource.locale.defaultActive', 'Default locale cannot be inactive.'),
  ('en', 'validation.resource.translation.key.min', 'Translation key must be at least 2 characters.'),
  ('en', 'validation.resource.translation.key.max', 'Translation key can be at most 140 characters.'),
  ('en', 'validation.resource.translation.key.pattern', 'Translation key may only include letters, numbers, dots, hyphens, and underscores.'),
  ('en', 'validation.resource.translation.locale', 'Select a valid locale.'),
  ('en', 'validation.resource.translation.value.min', 'Translation value cannot be empty.'),
  ('en', 'validation.resource.translation.value.max', 'Translation value can be at most 4000 characters.')
ON CONFLICT(`locale`, `key`) DO UPDATE SET
  `value` = excluded.`value`,
  `updated_at` = (unixepoch() * 1000);
