INSERT INTO `translations` (`locale`, `key`, `value`)
VALUES
  ('tr', 'dashboard.logging.exportAction', 'Excel olarak indir'),
  ('tr', 'dashboard.logging.auditExportTitle', 'Audit kayitlarini disa aktar'),
  ('tr', 'dashboard.logging.auditExportDescription', 'Secilen araliktaki audit kayitlari Excel uyumlu dosya olarak indirilir.'),
  ('tr', 'dashboard.logging.auditDeleteTitle', 'Audit kayitlarini temizle'),
  ('tr', 'dashboard.logging.auditDeleteDescription', 'Secilen araliktaki audit kayitlari kalici olarak silinir.'),
  ('tr', 'dashboard.logging.errorExportTitle', 'Hata kayitlarini disa aktar'),
  ('tr', 'dashboard.logging.errorExportDescription', 'Secilen araliktaki hata kayitlari Excel uyumlu dosya olarak indirilir.'),
  ('tr', 'dashboard.logging.errorDeleteTitle', 'Hata kayitlarini temizle'),
  ('tr', 'dashboard.logging.errorDeleteDescription', 'Secilen araliktaki hata kayitlari kalici olarak silinir.'),
  ('tr', 'dashboard.logging.deleteHistorySuccess', '{count} audit logu silindi.'),
  ('tr', 'dashboard.logging.deleteErrorsSuccess', '{count} hata logu silindi.'),
  ('tr', 'dashboard.logging.exportLimitError', 'Secilen araliktaki en fazla 1000 kayit indirilebilir. Araligi daraltin.'),
  ('tr', 'dashboard.logging.paginationPreviousLabel', 'Onceki'),
  ('tr', 'dashboard.logging.paginationNextLabel', 'Sonraki'),
  ('tr', 'dashboard.logging.table.category', 'Kategori'),
  ('tr', 'dashboard.logging.table.method', 'Metot'),
  ('tr', 'dashboard.logging.table.resource', 'Kaynak'),
  ('tr', 'dashboard.logging.table.statusCode', 'Durum'),
  ('tr', 'dashboard.logging.table.target', 'Hedef'),
  ('tr', 'dashboard.logging.table.locale', 'Dil'),
  ('tr', 'dashboard.logging.table.fingerprint', 'Parmak izi'),
  ('en', 'dashboard.logging.exportAction', 'Download Excel'),
  ('en', 'dashboard.logging.auditExportTitle', 'Export audit logs'),
  ('en', 'dashboard.logging.auditExportDescription', 'Download audit logs in the selected range as an Excel-compatible file.'),
  ('en', 'dashboard.logging.auditDeleteTitle', 'Delete audit logs'),
  ('en', 'dashboard.logging.auditDeleteDescription', 'Permanently delete audit logs in the selected date range.'),
  ('en', 'dashboard.logging.errorExportTitle', 'Export error logs'),
  ('en', 'dashboard.logging.errorExportDescription', 'Download error logs in the selected range as an Excel-compatible file.'),
  ('en', 'dashboard.logging.errorDeleteTitle', 'Delete error logs'),
  ('en', 'dashboard.logging.errorDeleteDescription', 'Permanently delete error logs in the selected date range.'),
  ('en', 'dashboard.logging.deleteHistorySuccess', '{count} audit logs deleted.'),
  ('en', 'dashboard.logging.deleteErrorsSuccess', '{count} error logs deleted.'),
  ('en', 'dashboard.logging.exportLimitError', 'The selected range can export at most 1000 rows. Narrow the date range.'),
  ('en', 'dashboard.logging.paginationPreviousLabel', 'Previous'),
  ('en', 'dashboard.logging.paginationNextLabel', 'Next'),
  ('en', 'dashboard.logging.table.category', 'Category'),
  ('en', 'dashboard.logging.table.method', 'Method'),
  ('en', 'dashboard.logging.table.resource', 'Resource'),
  ('en', 'dashboard.logging.table.statusCode', 'Status'),
  ('en', 'dashboard.logging.table.target', 'Target'),
  ('en', 'dashboard.logging.table.locale', 'Locale'),
  ('en', 'dashboard.logging.table.fingerprint', 'Fingerprint')
ON CONFLICT(`locale`, `key`) DO UPDATE SET
  `value` = excluded.`value`,
  `updated_at` = (unixepoch() * 1000);
