INSERT INTO `translations` (`locale`, `key`, `value`)
VALUES
  ('tr', 'dashboard.settings.account.cardIdentityDescription', 'Bir sonraki fazda configuration parameter kayitlarina donusecek cekirdek hesap satirlari.'),
  ('tr', 'dashboard.settings.account.cardIdentityEyebrow', 'Kimlik kayitlari'),
  ('tr', 'dashboard.settings.account.cardIdentityTitle', 'Hesap cekirdegi'),
  ('tr', 'dashboard.settings.account.cardPresenceDescription', 'Public yuzeylerde gorunecek sosyal ve iletisim kanallari icin mock baglanti iskeleti.'),
  ('tr', 'dashboard.settings.account.cardPresenceEyebrow', 'Public baglantilar'),
  ('tr', 'dashboard.settings.account.cardPresenceTitle', 'Dijital gorunurluk'),
  ('tr', 'dashboard.settings.account.checklistDescription', 'Bu mock tasarim, bir sonraki configuration parameter gorevinin UI iskeletini simdiden sabitler.'),
  ('tr', 'dashboard.settings.account.checklistTitle', 'Sonraki baglanti'),
  ('tr', 'dashboard.settings.account.description', 'Hesap, public link ve proje kimligi satirlarini popup-temelli editor akisi icin hazirlayan mock liste.'),
  ('tr', 'dashboard.settings.account.eyebrow', 'Hesap katmani'),
  ('tr', 'dashboard.settings.account.title', 'Account tabi'),
  ('tr', 'dashboard.settings.appearance.cardChromeDescription', 'Dashboard kabugundeki grid, panel ve focus state tercihleri ayni retro comic dilinde hizalanir.'),
  ('tr', 'dashboard.settings.appearance.cardChromeEyebrow', 'Yuzey dili'),
  ('tr', 'dashboard.settings.appearance.cardChromeTitle', 'Dashboard chrome'),
  ('tr', 'dashboard.settings.appearance.cardVoiceDescription', 'Bilingual copy ve editorial ton mock satirlar uzerinden korunur.'),
  ('tr', 'dashboard.settings.appearance.cardVoiceEyebrow', 'Icerik tonu'),
  ('tr', 'dashboard.settings.appearance.cardVoiceTitle', 'Yazi sistemi'),
  ('tr', 'dashboard.settings.appearance.checklistDescription', 'Gercek tercih depolamasi gelmeden once tasarim kararlarini gorunur tutan referans katmani.'),
  ('tr', 'dashboard.settings.appearance.checklistTitle', 'Mock tema notlari'),
  ('tr', 'dashboard.settings.appearance.description', 'Tema, tipografi ve dashboard density kararlarini gercek preference katmani gelmeden once sabitleyen gorunum.'),
  ('tr', 'dashboard.settings.appearance.eyebrow', 'Gorunum katmani'),
  ('tr', 'dashboard.settings.appearance.title', 'Appearance tabi'),
  ('tr', 'dashboard.settings.currentRoleLabel', 'Mevcut rol'),
  ('tr', 'dashboard.settings.metricGuardRails', 'Koruma katmani'),
  ('tr', 'dashboard.settings.metricProfileFields', 'Mock alan'),
  ('tr', 'dashboard.settings.metricRuntimeSurfaces', 'Runtime yuzeyi'),
  ('tr', 'dashboard.settings.metricTabCount', 'Tab modulu'),
  ('tr', 'dashboard.settings.mockBadge', 'Mock only'),
  ('tr', 'dashboard.settings.mockDescription', 'Bu ekran bilincli olarak read-only tasarlandi. Ama amac, sonraki account ve cache gorevleri icin kalici tab iskeletini simdiden olusturmak.'),
  ('tr', 'dashboard.settings.pageDescription', 'Tabbed settings page tasarimini server-first bir mock yuzey olarak ac; gercek mutation davranisi daha sonraki task''lerde eklenecek.'),
  ('tr', 'dashboard.settings.pageEyebrow', 'Ayar orchestrasyonu'),
  ('tr', 'dashboard.settings.pageTitle', 'Dashboard ayarlari'),
  ('tr', 'dashboard.settings.restrictedDescription', 'Bu settings yuzeyini gormek icin gerekli claim sizde yok.'),
  ('tr', 'dashboard.settings.restrictedTitle', 'Kisitli akis'),
  ('tr', 'dashboard.settings.runtime.cardCacheDescription', 'I18n ve gelecek configuration parameter cache''i ayni invalidation dilini paylasacak sekilde planlandi.'),
  ('tr', 'dashboard.settings.runtime.cardCacheEyebrow', 'Cache yolu'),
  ('tr', 'dashboard.settings.runtime.cardCacheTitle', 'Runtime cache kontrati'),
  ('tr', 'dashboard.settings.runtime.cardDeliveryDescription', 'Cloudflare Pages, D1 ve Worker kisitlari tek sayfalik bir kontrol paneli mantiginda gorunur tutuluyor.'),
  ('tr', 'dashboard.settings.runtime.cardDeliveryEyebrow', 'Dagitim yuzeyi'),
  ('tr', 'dashboard.settings.runtime.cardDeliveryTitle', 'Edge teslimati'),
  ('tr', 'dashboard.settings.runtime.checklistDescription', 'Cache temizleme butonu ve config warm-up gibi gercek operasyonlar icin hazir bekleyen gorev listesi.'),
  ('tr', 'dashboard.settings.runtime.checklistTitle', 'Bekleyen runtime aksiyonlari'),
  ('tr', 'dashboard.settings.runtime.description', 'Cache, deployment ve observability yuzeylerini settings modulu altinda toplayan mock runtime gorunumu.'),
  ('tr', 'dashboard.settings.runtime.eyebrow', 'Runtime katmani'),
  ('tr', 'dashboard.settings.runtime.title', 'Runtime tabi'),
  ('tr', 'dashboard.settings.security.cardAccessDescription', 'Loader-first authz gate ve settings.manage claim''i mock tasarim icinde de acikca gorunur.'),
  ('tr', 'dashboard.settings.security.cardAccessEyebrow', 'Erisim cercevesi'),
  ('tr', 'dashboard.settings.security.cardAccessTitle', 'Yetki modeli'),
  ('tr', 'dashboard.settings.security.cardSessionDescription', 'Session ve audit beklentileri, ilerideki gercek settings mutasyonlarinin guvenlik limitlerini tarif eder.'),
  ('tr', 'dashboard.settings.security.cardSessionEyebrow', 'Session kurali'),
  ('tr', 'dashboard.settings.security.cardSessionTitle', 'Oturum posturu'),
  ('tr', 'dashboard.settings.security.checklistDescription', 'Mutasyonlar gelmeden once bile guvenlik beklentilerini sayfa ustunde belgelendiren kontrol listesi.'),
  ('tr', 'dashboard.settings.security.checklistTitle', 'Koruma notlari'),
  ('tr', 'dashboard.settings.security.description', 'Session, authz ve audit beklentilerini gercek kayit akislarindan once tanimlayan koruma tab''i.'),
  ('tr', 'dashboard.settings.security.eyebrow', 'Guvenlik katmani'),
  ('tr', 'dashboard.settings.security.title', 'Security tabi'),
  ('tr', 'dashboard.settings.tab.account', 'Account'),
  ('tr', 'dashboard.settings.tab.appearance', 'Appearance'),
  ('tr', 'dashboard.settings.tab.runtime', 'Runtime'),
  ('tr', 'dashboard.settings.tab.security', 'Security'),
  ('en', 'dashboard.settings.account.cardIdentityDescription', 'Core account rows that will map to configuration parameters in the next phase.'),
  ('en', 'dashboard.settings.account.cardIdentityEyebrow', 'Identity registry'),
  ('en', 'dashboard.settings.account.cardIdentityTitle', 'Account core'),
  ('en', 'dashboard.settings.account.cardPresenceDescription', 'Mock social and contact links that will later power public profile surfaces.'),
  ('en', 'dashboard.settings.account.cardPresenceEyebrow', 'Public links'),
  ('en', 'dashboard.settings.account.cardPresenceTitle', 'Digital presence'),
  ('en', 'dashboard.settings.account.checklistDescription', 'This mock layout locks the UI skeleton for the upcoming configuration-parameter task.'),
  ('en', 'dashboard.settings.account.checklistTitle', 'Next handoff'),
  ('en', 'dashboard.settings.account.description', 'A mock list surface that prepares account, public link, and project identity rows for a popup editor flow.'),
  ('en', 'dashboard.settings.account.eyebrow', 'Account layer'),
  ('en', 'dashboard.settings.account.title', 'Account tab'),
  ('en', 'dashboard.settings.appearance.cardChromeDescription', 'Grid, panel, and focus-state decisions stay aligned to the same retro comic dashboard language.'),
  ('en', 'dashboard.settings.appearance.cardChromeEyebrow', 'Surface language'),
  ('en', 'dashboard.settings.appearance.cardChromeTitle', 'Dashboard chrome'),
  ('en', 'dashboard.settings.appearance.cardVoiceDescription', 'Bilingual copy and editorial tone are preserved through mock planning rows.'),
  ('en', 'dashboard.settings.appearance.cardVoiceEyebrow', 'Content voice'),
  ('en', 'dashboard.settings.appearance.cardVoiceTitle', 'Writing system'),
  ('en', 'dashboard.settings.appearance.checklistDescription', 'A reference layer that keeps design decisions visible until real preference storage arrives.'),
  ('en', 'dashboard.settings.appearance.checklistTitle', 'Mock theme notes'),
  ('en', 'dashboard.settings.appearance.description', 'A planning view that stabilizes theme, typography, and dashboard density decisions before a real preference layer exists.'),
  ('en', 'dashboard.settings.appearance.eyebrow', 'Appearance layer'),
  ('en', 'dashboard.settings.appearance.title', 'Appearance tab'),
  ('en', 'dashboard.settings.currentRoleLabel', 'Current role'),
  ('en', 'dashboard.settings.metricGuardRails', 'Guard rails'),
  ('en', 'dashboard.settings.metricProfileFields', 'Mock fields'),
  ('en', 'dashboard.settings.metricRuntimeSurfaces', 'Runtime surfaces'),
  ('en', 'dashboard.settings.metricTabCount', 'Tab modules'),
  ('en', 'dashboard.settings.mockBadge', 'Mock only'),
  ('en', 'dashboard.settings.mockDescription', 'This screen is intentionally read-only. The goal is to lock the long-lived tab skeleton before account and cache mutations arrive in later tasks.'),
  ('en', 'dashboard.settings.pageDescription', 'Open the tabbed settings page as a server-first mock surface; real mutation behavior will land in later tasks.'),
  ('en', 'dashboard.settings.pageEyebrow', 'Settings orchestration'),
  ('en', 'dashboard.settings.pageTitle', 'Dashboard settings'),
  ('en', 'dashboard.settings.restrictedDescription', 'You do not have the claim required to view this settings surface.'),
  ('en', 'dashboard.settings.restrictedTitle', 'Restricted flow'),
  ('en', 'dashboard.settings.runtime.cardCacheDescription', 'The existing i18n cache and future configuration-parameter cache are planned around the same invalidation language.'),
  ('en', 'dashboard.settings.runtime.cardCacheEyebrow', 'Cache path'),
  ('en', 'dashboard.settings.runtime.cardCacheTitle', 'Runtime cache contract'),
  ('en', 'dashboard.settings.runtime.cardDeliveryDescription', 'Cloudflare Pages, D1, and Worker runtime constraints stay visible through a single planning panel.'),
  ('en', 'dashboard.settings.runtime.cardDeliveryEyebrow', 'Delivery surface'),
  ('en', 'dashboard.settings.runtime.cardDeliveryTitle', 'Edge delivery'),
  ('en', 'dashboard.settings.runtime.checklistDescription', 'A ready backlog for real operations such as cache purge and config warm-up.'),
  ('en', 'dashboard.settings.runtime.checklistTitle', 'Pending runtime actions'),
  ('en', 'dashboard.settings.runtime.description', 'A mock runtime view that groups cache, deployment, and observability surfaces under the settings module.'),
  ('en', 'dashboard.settings.runtime.eyebrow', 'Runtime layer'),
  ('en', 'dashboard.settings.runtime.title', 'Runtime tab'),
  ('en', 'dashboard.settings.security.cardAccessDescription', 'The loader-first authz gate and settings.manage claim remain explicit even in the mock phase.'),
  ('en', 'dashboard.settings.security.cardAccessEyebrow', 'Access frame'),
  ('en', 'dashboard.settings.security.cardAccessTitle', 'Authorization model'),
  ('en', 'dashboard.settings.security.cardSessionDescription', 'Session and audit expectations define the security ceiling for future settings mutations.'),
  ('en', 'dashboard.settings.security.cardSessionEyebrow', 'Session policy'),
  ('en', 'dashboard.settings.security.cardSessionTitle', 'Session posture'),
  ('en', 'dashboard.settings.security.checklistDescription', 'A visible control list that documents security expectations before mutations ship.'),
  ('en', 'dashboard.settings.security.checklistTitle', 'Protection notes'),
  ('en', 'dashboard.settings.security.description', 'A guard-rail tab that defines session, authz, and audit expectations before real persistence lands.'),
  ('en', 'dashboard.settings.security.eyebrow', 'Security layer'),
  ('en', 'dashboard.settings.security.title', 'Security tab'),
  ('en', 'dashboard.settings.tab.account', 'Account'),
  ('en', 'dashboard.settings.tab.appearance', 'Appearance'),
  ('en', 'dashboard.settings.tab.runtime', 'Runtime'),
  ('en', 'dashboard.settings.tab.security', 'Security')
ON CONFLICT(`locale`, `key`) DO UPDATE SET
  `value` = excluded.`value`,
  `updated_at` = (unixepoch() * 1000);
