CREATE TABLE `configuration_parameters` (
  `key` text PRIMARY KEY NOT NULL,
  `value` text NOT NULL,
  `created_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
  `updated_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
  CONSTRAINT `configuration_parameters_key_length_check` CHECK(length(`key`) between 3 and 120),
  CONSTRAINT `configuration_parameters_key_spacing_check` CHECK(instr(`key`, ' ') = 0)
);

INSERT INTO `configuration_parameters` (`key`, `value`)
VALUES
  ('site.name', 'Paper Ink'),
  ('site.domainUrl', 'https://paper-portfolio-ink.dev'),
  ('contact.email', 'admin@paper-portfolio-ink.dev'),
  ('social.linkedin', 'https://linkedin.com/in/enes-ink'),
  ('social.github', 'https://github.com/enesonmez'),
  ('social.x', 'https://x.com/paperinkdev'),
  ('social.instagram', 'https://instagram.com/paperportfolioink')
ON CONFLICT(`key`) DO UPDATE SET
  `value` = excluded.`value`,
  `updated_at` = (unixepoch() * 1000);

INSERT INTO `translations` (`locale`, `key`, `value`)
VALUES
  ('tr', 'dashboard.settings.account.actionLabel', 'Kaydi duzenle'),
  ('tr', 'dashboard.settings.account.cardIdentityDescription', 'Proje cekirdegi ve iletisim kanali cache-backed configuration parameter kayitlarindan okunur.'),
  ('tr', 'dashboard.settings.account.cardIdentityEyebrow', 'Kimlik kayitlari'),
  ('tr', 'dashboard.settings.account.cardIdentityTitle', 'Hesap cekirdegi'),
  ('tr', 'dashboard.settings.account.cardPresenceDescription', 'Public yuzeylerde kullanilacak sosyal linkler ayni key-value registry uzerinden yonetilir.'),
  ('tr', 'dashboard.settings.account.cardPresenceEyebrow', 'Public baglantilar'),
  ('tr', 'dashboard.settings.account.cardPresenceTitle', 'Dijital gorunurluk'),
  ('tr', 'dashboard.settings.account.checklistDescription', 'Bu tab ilk request sonrasi isinan configuration cache''ini kullanan modal tabanli edit akisidir.'),
  ('tr', 'dashboard.settings.account.checklistTitle', 'Isletim notlari'),
  ('tr', 'dashboard.settings.account.description', 'Email, sosyal linkler ve proje kimligini list-first yuzeyde tutan account registry.'),
  ('tr', 'dashboard.settings.account.editDescription', 'Secili configuration parameter degerini guncelle. Kayit D1''e yazilir ve configuration cache temizlenir.'),
  ('tr', 'dashboard.settings.account.editTitle', 'Account kaydini guncelle'),
  ('tr', 'dashboard.settings.account.eyebrow', 'Hesap katmani'),
  ('tr', 'dashboard.settings.account.field.contact.email.hint', 'Public iletisim ve admin kimlik rotalari icin birincil e-posta.'),
  ('tr', 'dashboard.settings.account.field.contact.email.label', 'Primary email'),
  ('tr', 'dashboard.settings.account.field.site.domainUrl.hint', 'Canonical site URL ve ilerideki metadata baglantilari.'),
  ('tr', 'dashboard.settings.account.field.site.domainUrl.label', 'Domain URL'),
  ('tr', 'dashboard.settings.account.field.site.name.hint', 'Public meta title ve portfolio kimligi icin temel proje adi.'),
  ('tr', 'dashboard.settings.account.field.site.name.label', 'Project name'),
  ('tr', 'dashboard.settings.account.field.social.github.hint', 'Repository ve acik kaynak profil baglantisi.'),
  ('tr', 'dashboard.settings.account.field.social.github.label', 'GitHub'),
  ('tr', 'dashboard.settings.account.field.social.instagram.hint', 'Gorsel paylasim ve brand stream linki.'),
  ('tr', 'dashboard.settings.account.field.social.instagram.label', 'Instagram'),
  ('tr', 'dashboard.settings.account.field.social.linkedin.hint', 'Profesyonel profil baglantisi.'),
  ('tr', 'dashboard.settings.account.field.social.linkedin.label', 'LinkedIn'),
  ('tr', 'dashboard.settings.account.field.social.x.hint', 'Kisa guncellemeler ve dagitim kanali.'),
  ('tr', 'dashboard.settings.account.field.social.x.label', 'X'),
  ('tr', 'dashboard.settings.account.title', 'Account tabi'),
  ('tr', 'dashboard.settings.account.valueFallback', 'Henuz ayarlanmadi'),
  ('tr', 'dashboard.settings.pageDescription', 'Tabbed settings page tasarimini server-first bir operasyon yuzeyine cevir; account tabi cache-backed kayitlari modal ile gunceller.'),
  ('tr', 'validation.settings.contactEmail', 'Gecerli bir e-posta adresi gir.'),
  ('tr', 'validation.settings.key', 'Gecerli bir configuration key sec.'),
  ('tr', 'validation.settings.projectName.max', 'Proje adi en fazla 80 karakter olabilir.'),
  ('tr', 'validation.settings.projectName.min', 'Proje adi en az 2 karakter olmali.'),
  ('tr', 'validation.settings.url', 'Gecerli bir URL gir.'),
  ('en', 'dashboard.settings.account.actionLabel', 'Edit record'),
  ('en', 'dashboard.settings.account.cardIdentityDescription', 'Project core and contact channels read from cache-backed configuration parameters.'),
  ('en', 'dashboard.settings.account.cardIdentityEyebrow', 'Identity registry'),
  ('en', 'dashboard.settings.account.cardIdentityTitle', 'Account core'),
  ('en', 'dashboard.settings.account.cardPresenceDescription', 'Public-facing social links are managed through the same key-value registry.'),
  ('en', 'dashboard.settings.account.cardPresenceEyebrow', 'Public links'),
  ('en', 'dashboard.settings.account.cardPresenceTitle', 'Digital presence'),
  ('en', 'dashboard.settings.account.checklistDescription', 'This tab uses the configuration cache that warms after the first request and edits through modal actions.'),
  ('en', 'dashboard.settings.account.checklistTitle', 'Operating notes'),
  ('en', 'dashboard.settings.account.description', 'An account registry that keeps email, social links, and project identity in a list-first surface.'),
  ('en', 'dashboard.settings.account.editDescription', 'Update the selected configuration parameter. The value is written to D1 and the configuration cache is purged.'),
  ('en', 'dashboard.settings.account.editTitle', 'Update account record'),
  ('en', 'dashboard.settings.account.eyebrow', 'Account layer'),
  ('en', 'dashboard.settings.account.field.contact.email.hint', 'Primary email used for public contact and admin identity flows.'),
  ('en', 'dashboard.settings.account.field.contact.email.label', 'Primary email'),
  ('en', 'dashboard.settings.account.field.site.domainUrl.hint', 'Canonical site URL and future metadata links.'),
  ('en', 'dashboard.settings.account.field.site.domainUrl.label', 'Domain URL'),
  ('en', 'dashboard.settings.account.field.site.name.hint', 'Base project name for public metadata and portfolio identity.'),
  ('en', 'dashboard.settings.account.field.site.name.label', 'Project name'),
  ('en', 'dashboard.settings.account.field.social.github.hint', 'Repository and open-source profile link.'),
  ('en', 'dashboard.settings.account.field.social.github.label', 'GitHub'),
  ('en', 'dashboard.settings.account.field.social.instagram.hint', 'Visual brand stream link.'),
  ('en', 'dashboard.settings.account.field.social.instagram.label', 'Instagram'),
  ('en', 'dashboard.settings.account.field.social.linkedin.hint', 'Professional profile link.'),
  ('en', 'dashboard.settings.account.field.social.linkedin.label', 'LinkedIn'),
  ('en', 'dashboard.settings.account.field.social.x.hint', 'Short updates and distribution channel.'),
  ('en', 'dashboard.settings.account.field.social.x.label', 'X'),
  ('en', 'dashboard.settings.account.title', 'Account tab'),
  ('en', 'dashboard.settings.account.valueFallback', 'Not configured yet'),
  ('en', 'dashboard.settings.pageDescription', 'Turn the tabbed settings page into a server-first operational surface; the account tab edits cache-backed records through a modal.'),
  ('en', 'validation.settings.contactEmail', 'Enter a valid email address.'),
  ('en', 'validation.settings.key', 'Select a valid configuration key.'),
  ('en', 'validation.settings.projectName.max', 'Project name can be at most 80 characters.'),
  ('en', 'validation.settings.projectName.min', 'Project name must be at least 2 characters.'),
  ('en', 'validation.settings.url', 'Enter a valid URL.')
ON CONFLICT(`locale`, `key`) DO UPDATE SET
  `value` = excluded.`value`,
  `updated_at` = (unixepoch() * 1000);
