INSERT INTO `translations` (`locale`, `key`, `value`)
VALUES
  ('tr', 'dashboard.users.accessActionLabel', 'Claim ve rol'),
  ('tr', 'dashboard.users.accessDescription', 'Rol degisimini kaydet ve claim override''larini modal uzerinden yonet.'),
  ('tr', 'dashboard.users.accessRoleSaveLabel', 'Rolu kaydet'),
  ('tr', 'dashboard.users.accessTitle', 'Yetki duzenle'),
  ('tr', 'dashboard.users.accessVersionLabel', 'Authz v'),
  ('tr', 'dashboard.users.claimDefineLabel', 'Tanimla'),
  ('tr', 'dashboard.users.claimEffectiveLabel', 'Efektif claim durumu'),
  ('tr', 'dashboard.users.claimGrantedLabel', 'Tanimli'),
  ('tr', 'dashboard.users.claimOverrideGrantLabel', 'Override grant'),
  ('tr', 'dashboard.users.claimOverrideRevokeLabel', 'Override revoke'),
  ('tr', 'dashboard.users.claimRegistryTitle', 'Claim override kayitlari'),
  ('tr', 'dashboard.users.claimRemoveLabel', 'Cikar'),
  ('tr', 'dashboard.users.claimRevokedLabel', 'Cikarildi'),
  ('tr', 'dashboard.users.claimRoleDefaultLabel', 'Rol varsayilani'),
  ('tr', 'dashboard.users.claimScopeLabel', 'Kapsam'),
  ('tr', 'dashboard.users.claimScopeNoneLabel', 'yok'),
  ('tr', 'dashboard.users.editDescription', 'Kimlik alanlarini guncelle veya parola rotasyonu yap.'),
  ('tr', 'dashboard.users.form.error.authzVersionMismatch', 'Bu kullanicinin yetki surumu degisti. Modal''i kapatip yeniden acin.'),
  ('tr', 'validation.user.authzVersion', 'Gecerli bir authz versiyonu gerekli.'),
  ('tr', 'validation.user.authorizationClaim', 'Gecerli bir authorization claim sec.'),
  ('en', 'dashboard.users.accessActionLabel', 'Claims and role'),
  ('en', 'dashboard.users.accessDescription', 'Save role changes and manage claim overrides from the same modal.'),
  ('en', 'dashboard.users.accessRoleSaveLabel', 'Save role'),
  ('en', 'dashboard.users.accessTitle', 'Edit access'),
  ('en', 'dashboard.users.accessVersionLabel', 'Authz v'),
  ('en', 'dashboard.users.claimDefineLabel', 'Grant'),
  ('en', 'dashboard.users.claimEffectiveLabel', 'Effective claim state'),
  ('en', 'dashboard.users.claimGrantedLabel', 'Granted'),
  ('en', 'dashboard.users.claimOverrideGrantLabel', 'Override grant'),
  ('en', 'dashboard.users.claimOverrideRevokeLabel', 'Override revoke'),
  ('en', 'dashboard.users.claimRegistryTitle', 'Claim override registry'),
  ('en', 'dashboard.users.claimRemoveLabel', 'Revoke'),
  ('en', 'dashboard.users.claimRevokedLabel', 'Revoked'),
  ('en', 'dashboard.users.claimRoleDefaultLabel', 'Role default'),
  ('en', 'dashboard.users.claimScopeLabel', 'Scope'),
  ('en', 'dashboard.users.claimScopeNoneLabel', 'none'),
  ('en', 'dashboard.users.editDescription', 'Update identity fields or rotate the credential password.'),
  ('en', 'dashboard.users.form.error.authzVersionMismatch', 'This user''s authorization version changed. Close and reopen the modal.'),
  ('en', 'validation.user.authzVersion', 'Provide a valid authz version.'),
  ('en', 'validation.user.authorizationClaim', 'Select a valid authorization claim.')
ON CONFLICT(`locale`, `key`) DO UPDATE SET
  `value` = excluded.`value`,
  `updated_at` = (unixepoch() * 1000);
