DELETE FROM `translations` WHERE `key` IN (
  'dashboard.settings.security.noOtherSessionsDescription',
  'dashboard.settings.account.checklist.item1',
  'dashboard.settings.account.checklist.item2',
  'dashboard.settings.account.checklist.item3',
  'dashboard.settings.appearance.cardChrome.row1.hint',
  'dashboard.settings.appearance.cardChrome.row1.label',
  'dashboard.settings.appearance.cardChrome.row1.value',
  'dashboard.settings.appearance.cardChrome.row2.hint',
  'dashboard.settings.appearance.cardChrome.row2.label',
  'dashboard.settings.appearance.cardChrome.row2.value',
  'dashboard.settings.appearance.cardChrome.row3.hint',
  'dashboard.settings.appearance.cardChrome.row3.label',
  'dashboard.settings.appearance.cardChrome.row3.value',
  'dashboard.settings.appearance.cardVoice.row1.hint',
  'dashboard.settings.appearance.cardVoice.row1.label',
  'dashboard.settings.appearance.cardVoice.row1.value',
  'dashboard.settings.appearance.cardVoice.row2.hint',
  'dashboard.settings.appearance.cardVoice.row2.label',
  'dashboard.settings.appearance.cardVoice.row2.value',
  'dashboard.settings.appearance.cardVoice.row3.hint',
  'dashboard.settings.appearance.cardVoice.row3.label',
  'dashboard.settings.appearance.cardVoice.row3.value',
  'dashboard.settings.appearance.checklist.item1',
  'dashboard.settings.appearance.checklist.item2',
  'dashboard.settings.appearance.checklist.item3',
  'dashboard.settings.security.cardSession.row1.hint',
  'dashboard.settings.security.cardSession.row1.label',
  'dashboard.settings.security.cardSession.row1.value',
  'dashboard.settings.security.cardSession.row2.hint',
  'dashboard.settings.security.cardSession.row2.label',
  'dashboard.settings.security.cardSession.row2.value',
  'dashboard.settings.security.cardSession.row3.hint',
  'dashboard.settings.security.cardSession.row3.label',
  'dashboard.settings.security.cardSession.row3.value',
  'dashboard.settings.security.cardAccess.row1.hint',
  'dashboard.settings.security.cardAccess.row1.label',
  'dashboard.settings.security.cardAccess.row1.value',
  'dashboard.settings.security.cardAccess.row2.hint',
  'dashboard.settings.security.cardAccess.row2.label',
  'dashboard.settings.security.cardAccess.row2.value',
  'dashboard.settings.security.cardAccess.row3.hint',
  'dashboard.settings.security.cardAccess.row3.label',
  'dashboard.settings.security.cardAccess.row3.value',
  'dashboard.settings.security.checklist.item1',
  'dashboard.settings.security.checklist.item2',
  'dashboard.settings.security.checklist.item3',
  'dashboard.settings.runtime.cardCache.row1.hint',
  'dashboard.settings.runtime.cardCache.row1.label',
  'dashboard.settings.runtime.cardCache.row1.value',
  'dashboard.settings.runtime.cardCache.row2.hint',
  'dashboard.settings.runtime.cardCache.row2.label',
  'dashboard.settings.runtime.cardCache.row2.value',
  'dashboard.settings.runtime.cardCache.row3.hint',
  'dashboard.settings.runtime.cardCache.row3.label',
  'dashboard.settings.runtime.cardCache.row3.value',
  'dashboard.settings.runtime.cardDelivery.row1.hint',
  'dashboard.settings.runtime.cardDelivery.row1.label',
  'dashboard.settings.runtime.cardDelivery.row1.value',
  'dashboard.settings.runtime.cardDelivery.row2.hint',
  'dashboard.settings.runtime.cardDelivery.row2.label',
  'dashboard.settings.runtime.cardDelivery.row2.value',
  'dashboard.settings.runtime.cardDelivery.row3.hint',
  'dashboard.settings.runtime.cardDelivery.row3.label',
  'dashboard.settings.runtime.cardDelivery.row3.value',
  'dashboard.settings.runtime.checklist.item1',
  'dashboard.settings.runtime.checklist.item2',
  'dashboard.settings.runtime.checklist.item3'
);

INSERT INTO `translations` (`locale`, `key`, `value`)
VALUES
  ('tr', 'dashboard.settings.security.noOtherSessionsDescription', 'Sistemde şu anda bekleyen toplu güvenlik eylemi bulunmuyor. Aktif olarak sadece sizin mevcut oturumunuz açık durumda.'),
  ('tr', 'dashboard.settings.account.checklist.item1', 'Satırlar liste öncelikli kalır; pop-up tek yazma yüzeyidir.'),
  ('tr', 'dashboard.settings.account.checklist.item2', 'Başarılı yazma işlemleri yapılandırma önbelleğini açıkça temizler.'),
  ('tr', 'dashboard.settings.account.checklist.item3', 'Genel tüketiciler aynı önbellek destekli sicili yeniden kullanabilir.'),
  ('tr', 'dashboard.settings.appearance.cardChrome.row1.hint', 'Tema yönü'),
  ('tr', 'dashboard.settings.appearance.cardChrome.row1.label', 'Yüzey modu'),
  ('tr', 'dashboard.settings.appearance.cardChrome.row1.value', 'Paper Comic / Comic Noir'),
  ('tr', 'dashboard.settings.appearance.cardChrome.row2.hint', 'Tipografi kilidi'),
  ('tr', 'dashboard.settings.appearance.cardChrome.row2.label', 'Başlık yazı tipi'),
  ('tr', 'dashboard.settings.appearance.cardChrome.row2.value', 'VT323'),
  ('tr', 'dashboard.settings.appearance.cardChrome.row3.hint', 'Tipografi kilidi'),
  ('tr', 'dashboard.settings.appearance.cardChrome.row3.label', 'Gövde yazı tipi'),
  ('tr', 'dashboard.settings.appearance.cardChrome.row3.value', 'JetBrains Mono'),
  ('tr', 'dashboard.settings.appearance.cardVoice.row1.hint', 'İçerik ritmi'),
  ('tr', 'dashboard.settings.appearance.cardVoice.row1.label', 'Dashboard tonu'),
  ('tr', 'dashboard.settings.appearance.cardVoice.row1.value', 'Minimal, doğrudan, operasyon öncelikli'),
  ('tr', 'dashboard.settings.appearance.cardVoice.row2.hint', 'Yerelleştirme şekli'),
  ('tr', 'dashboard.settings.appearance.cardVoice.row2.label', 'Metin kapsamı'),
  ('tr', 'dashboard.settings.appearance.cardVoice.row2.value', 'TR / EN tohum destekli'),
  ('tr', 'dashboard.settings.appearance.cardVoice.row3.hint', 'Yoğunluk politikası'),
  ('tr', 'dashboard.settings.appearance.cardVoice.row3.label', 'Panel aralığı'),
  ('tr', 'dashboard.settings.appearance.cardVoice.row3.value', 'Sert sınırlara sahip kompakt ızgara'),
  ('tr', 'dashboard.settings.appearance.checklist.item1', 'Glow (parıltı) yok, yuvarlatılmış kurumsal kabuklar yok.'),
  ('tr', 'dashboard.settings.appearance.checklist.item2', 'Odak durumları yüksek kontrastlı ve görünür kalır.'),
  ('tr', 'dashboard.settings.appearance.checklist.item3', 'Gelecekteki bir görünüm tercihi katmanı SSR varsayılanlarını bozmamalıdır.'),
  ('tr', 'dashboard.settings.security.cardSession.row1.hint', 'Çerez kontratı'),
  ('tr', 'dashboard.settings.security.cardSession.row1.label', 'Oturum depolama'),
  ('tr', 'dashboard.settings.security.cardSession.row1.value', 'HttpOnly / Secure / SameSite=Lax'),
  ('tr', 'dashboard.settings.security.cardSession.row2.hint', 'Denetim kontratı'),
  ('tr', 'dashboard.settings.security.cardSession.row2.label', 'Mutasyon loglama'),
  ('tr', 'dashboard.settings.security.cardSession.row2.value', 'Ayarlar yazmaları için gerekli'),
  ('tr', 'dashboard.settings.security.cardSession.row3.hint', 'Edge politikası'),
  ('tr', 'dashboard.settings.security.cardSession.row3.label', 'Çalışma zamanı duruşu'),
  ('tr', 'dashboard.settings.security.cardSession.row3.value', 'Yalnızca Cloudflare Worker uyumlu'),
  ('tr', 'dashboard.settings.security.cardAccess.row1.hint', 'Hak kapısı'),
  ('tr', 'dashboard.settings.security.cardAccess.row1.label', 'Sayfa erişimi'),
  ('tr', 'dashboard.settings.security.cardAccess.row1.value', 'settings.security.manage.own/any'),
  ('tr', 'dashboard.settings.security.cardAccess.row2.hint', 'Rota stratejisi'),
  ('tr', 'dashboard.settings.security.cardAccess.row2.label', 'Veri akışı'),
  ('tr', 'dashboard.settings.security.cardAccess.row2.value', 'Öncelikle yükleyici, sunucu onaylı'),
  ('tr', 'dashboard.settings.security.cardAccess.row3.hint', 'Gelecek inceleme'),
  ('tr', 'dashboard.settings.security.cardAccess.row3.label', 'Hak editörü'),
  ('tr', 'dashboard.settings.security.cardAccess.row3.value', 'Kullanıcı modal görevi beklemede'),
  ('tr', 'dashboard.settings.security.checklist.item1', 'Satır seviyesinde intent doğrulaması olmadan ayar mutasyonlarını asla açığa çıkarmayın.'),
  ('tr', 'dashboard.settings.security.checklist.item2', 'Yapılandırma değişikliklerinden sonra önbellek temizleme açık kalmalıdır.'),
  ('tr', 'dashboard.settings.security.checklist.item3', 'Yetkilendirme güncellemeleri revizyon tabanlı geçersiz kılmayı korumalıdır.'),
  ('tr', 'dashboard.settings.runtime.cardCache.row1.hint', 'Mevcut akış'),
  ('tr', 'dashboard.settings.runtime.cardCache.row1.label', 'I18n önbelleği'),
  ('tr', 'dashboard.settings.runtime.cardCache.row1.value', 'İlk istekten sonra ısınır'),
  ('tr', 'dashboard.settings.runtime.cardCache.row2.hint', 'Mevcut akış'),
  ('tr', 'dashboard.settings.runtime.cardCache.row2.label', 'Yapılandırma önbelleği'),
  ('tr', 'dashboard.settings.runtime.cardCache.row2.value', 'İlk istekten sonra ısınır'),
  ('tr', 'dashboard.settings.runtime.cardCache.row3.hint', 'Operatör eylemi'),
  ('tr', 'dashboard.settings.runtime.cardCache.row3.label', 'Temizleme tetikleyicisi'),
  ('tr', 'dashboard.settings.runtime.cardCache.row3.value', 'Ayarlar mutasyon geçersiz kılması'),
  ('tr', 'dashboard.settings.runtime.cardDelivery.row1.hint', 'Çalışma zamanı hedefi'),
  ('tr', 'dashboard.settings.runtime.cardDelivery.row1.label', 'Platform'),
  ('tr', 'dashboard.settings.runtime.cardDelivery.row1.value', 'Cloudflare Pages + D1'),
  ('tr', 'dashboard.settings.runtime.cardDelivery.row2.hint', 'Taşınabilirlik çizgisi'),
  ('tr', 'dashboard.settings.runtime.cardDelivery.row2.label', 'Adaptasyon'),
  ('tr', 'dashboard.settings.runtime.cardDelivery.row2.value', 'Sağlayıcı soyutlamaları paylaşılan kalır'),
  ('tr', 'dashboard.settings.runtime.cardDelivery.row3.hint', 'Gözlemlenebilirlik'),
  ('tr', 'dashboard.settings.runtime.cardDelivery.row3.label', 'Hata ayıklama izi'),
  ('tr', 'dashboard.settings.runtime.cardDelivery.row3.value', 'İstek kimliği + merkezi hata hattı'),
  ('tr', 'dashboard.settings.runtime.checklist.item1', 'Çalışma zamanı sekmesinde her önbelleğe alınmış sicil için açık önbellek kontrolleri ekleyin.'),
  ('tr', 'dashboard.settings.runtime.checklist.item2', 'Isınma ve geçersiz kılma yardımcı programlarını rota modüllerinin dışında tutun.'),
  ('tr', 'dashboard.settings.runtime.checklist.item3', 'Çalışma zamanı durum kartlarını varsayılan olarak yalnızca istemci tarafı sorgulamasına bağlamayın.'),

  ('en', 'dashboard.settings.security.noOtherSessionsDescription', 'There are currently no pending bulk security actions. Active only is your current session open.'),
  ('en', 'dashboard.settings.account.checklist.item1', 'Rows stay list-first; the popup is the only write surface.'),
  ('en', 'dashboard.settings.account.checklist.item2', 'Successful writes purge the configuration cache explicitly.'),
  ('en', 'dashboard.settings.account.checklist.item3', 'Public consumers can reuse the same cache-backed registry.'),
  ('en', 'dashboard.settings.appearance.cardChrome.row1.hint', 'Theme direction'),
  ('en', 'dashboard.settings.appearance.cardChrome.row1.label', 'Surface mode'),
  ('en', 'dashboard.settings.appearance.cardChrome.row1.value', 'Paper Comic / Comic Noir'),
  ('en', 'dashboard.settings.appearance.cardChrome.row2.hint', 'Typography lock'),
  ('en', 'dashboard.settings.appearance.cardChrome.row2.label', 'Heading font'),
  ('en', 'dashboard.settings.appearance.cardChrome.row2.value', 'VT323'),
  ('en', 'dashboard.settings.appearance.cardChrome.row3.hint', 'Typography lock'),
  ('en', 'dashboard.settings.appearance.cardChrome.row3.label', 'Body font'),
  ('en', 'dashboard.settings.appearance.cardChrome.row3.value', 'JetBrains Mono'),
  ('en', 'dashboard.settings.appearance.cardVoice.row1.hint', 'Content rhythm'),
  ('en', 'dashboard.settings.appearance.cardVoice.row1.label', 'Dashboard tone'),
  ('en', 'dashboard.settings.appearance.cardVoice.row1.value', 'Minimal, direct, operation-first'),
  ('en', 'dashboard.settings.appearance.cardVoice.row2.hint', 'Localization shape'),
  ('en', 'dashboard.settings.appearance.cardVoice.row2.label', 'Copy coverage'),
  ('en', 'dashboard.settings.appearance.cardVoice.row2.value', 'TR / EN seed-backed'),
  ('en', 'dashboard.settings.appearance.cardVoice.row3.hint', 'Density policy'),
  ('en', 'dashboard.settings.appearance.cardVoice.row3.label', 'Panel spacing'),
  ('en', 'dashboard.settings.appearance.cardVoice.row3.value', 'Compact grid with hard borders'),
  ('en', 'dashboard.settings.appearance.checklist.item1', 'No glow, no rounded enterprise shells.'),
  ('en', 'dashboard.settings.appearance.checklist.item2', 'Focus states remain high-contrast and visible.'),
  ('en', 'dashboard.settings.appearance.checklist.item3', 'A future appearance preference layer should not break SSR defaults.'),
  ('en', 'dashboard.settings.security.cardSession.row1.hint', 'Cookie contract'),
  ('en', 'dashboard.settings.security.cardSession.row1.label', 'Session storage'),
  ('en', 'dashboard.settings.security.cardSession.row1.value', 'HttpOnly / Secure / SameSite=Lax'),
  ('en', 'dashboard.settings.security.cardSession.row2.hint', 'Audit contract'),
  ('en', 'dashboard.settings.security.cardSession.row2.label', 'Mutation logging'),
  ('en', 'dashboard.settings.security.cardSession.row2.value', 'Required for settings writes'),
  ('en', 'dashboard.settings.security.cardSession.row3.hint', 'Edge policy'),
  ('en', 'dashboard.settings.security.cardSession.row3.label', 'Runtime posture'),
  ('en', 'dashboard.settings.security.cardSession.row3.value', 'Cloudflare Worker-compatible only'),
  ('en', 'dashboard.settings.security.cardAccess.row1.hint', 'Claim gate'),
  ('en', 'dashboard.settings.security.cardAccess.row1.label', 'Page access'),
  ('en', 'dashboard.settings.security.cardAccess.row1.value', 'settings.security.manage.own/any'),
  ('en', 'dashboard.settings.security.cardAccess.row2.hint', 'Route strategy'),
  ('en', 'dashboard.settings.security.cardAccess.row2.label', 'Data flow'),
  ('en', 'dashboard.settings.security.cardAccess.row2.value', 'Loader-first, server-authorized'),
  ('en', 'dashboard.settings.security.cardAccess.row3.hint', 'Future review'),
  ('en', 'dashboard.settings.security.cardAccess.row3.label', 'Claim editor'),
  ('en', 'dashboard.settings.security.cardAccess.row3.value', 'User modal task pending'),
  ('en', 'dashboard.settings.security.checklist.item1', 'Never expose settings mutations without row-level intent validation.'),
  ('en', 'dashboard.settings.security.checklist.item2', 'Cache purge must remain explicit after config changes.'),
  ('en', 'dashboard.settings.security.checklist.item3', 'Authorization updates should preserve revision-based invalidation.'),
  ('en', 'dashboard.settings.runtime.cardCache.row1.hint', 'Existing flow'),
  ('en', 'dashboard.settings.runtime.cardCache.row1.label', 'I18n cache'),
  ('en', 'dashboard.settings.runtime.cardCache.row1.value', 'Warm after first request'),
  ('en', 'dashboard.settings.runtime.cardCache.row2.hint', 'Current flow'),
  ('en', 'dashboard.settings.runtime.cardCache.row2.label', 'Configuration cache'),
  ('en', 'dashboard.settings.runtime.cardCache.row2.value', 'Warm after first request'),
  ('en', 'dashboard.settings.runtime.cardCache.row3.hint', 'Operator action'),
  ('en', 'dashboard.settings.runtime.cardCache.row3.label', 'Purge trigger'),
  ('en', 'dashboard.settings.runtime.cardCache.row3.value', 'Settings mutation invalidation'),
  ('en', 'dashboard.settings.runtime.cardDelivery.row1.hint', 'Runtime target'),
  ('en', 'dashboard.settings.runtime.cardDelivery.row1.label', 'Platform'),
  ('en', 'dashboard.settings.runtime.cardDelivery.row1.value', 'Cloudflare Pages + D1'),
  ('en', 'dashboard.settings.runtime.cardDelivery.row2.hint', 'Portability line'),
  ('en', 'dashboard.settings.runtime.cardDelivery.row2.label', 'Adaptation'),
  ('en', 'dashboard.settings.runtime.cardDelivery.row2.value', 'Provider abstractions stay shared'),
  ('en', 'dashboard.settings.runtime.cardDelivery.row3.hint', 'Observability'),
  ('en', 'dashboard.settings.runtime.cardDelivery.row3.label', 'Debug trail'),
  ('en', 'dashboard.settings.runtime.cardDelivery.row3.value', 'Request id + centralized error pipeline'),
  ('en', 'dashboard.settings.runtime.checklist.item1', 'Add explicit cache controls for each cached registry in the runtime tab.'),
  ('en', 'dashboard.settings.runtime.checklist.item2', 'Keep warm-up and invalidation utilities outside route modules.'),
  ('en', 'dashboard.settings.runtime.checklist.item3', 'Do not couple runtime status cards to client-only polling by default.')
ON CONFLICT(`locale`, `key`) DO UPDATE SET
  `value` = excluded.`value`,
  `updated_at` = (unixepoch() * 1000);
