DELETE FROM `translations`
WHERE `key` IN (
  'dashboard.settings.runtime.checklistDescription',
  'dashboard.settings.runtime.checklistTitle',
  'dashboard.settings.runtime.description',
  'dashboard.settings.runtime.cacheKeyLabel',
  'dashboard.settings.runtime.cacheScopeLabel',
  'dashboard.settings.runtime.cacheStrategyLabel',
  'dashboard.settings.runtime.cacheValueLabel',
  'dashboard.settings.runtime.warmScopeLabel',
  'dashboard.settings.runtime.refreshAction',
  'dashboard.settings.runtime.refreshPending',
  'dashboard.settings.runtime.scope.actor',
  'dashboard.settings.runtime.scope.global',
  'dashboard.settings.runtime.scope.locale',
  'dashboard.settings.runtime.scope.page',
  'dashboard.settings.runtime.strategy.cloudflare',
  'dashboard.settings.runtime.strategy.memory',
  'dashboard.settings.runtime.strategy.none',
  'dashboard.settings.runtime.value.keys',
  'dashboard.settings.runtime.value.locales',
  'dashboard.settings.runtime.value.page',
  'dashboard.settings.runtime.value.revision',
  'dashboard.settings.runtime.entry.configuration.eyebrow',
  'dashboard.settings.runtime.entry.configuration.title',
  'dashboard.settings.runtime.entry.configuration.description',
  'dashboard.settings.runtime.entry.i18n.eyebrow',
  'dashboard.settings.runtime.entry.i18n.title',
  'dashboard.settings.runtime.entry.i18n.description',
  'dashboard.settings.runtime.entry.publicHome.eyebrow',
  'dashboard.settings.runtime.entry.publicHome.title',
  'dashboard.settings.runtime.entry.publicHome.description',
  'dashboard.settings.runtime.entry.publicProjects.eyebrow',
  'dashboard.settings.runtime.entry.publicProjects.title',
  'dashboard.settings.runtime.entry.publicProjects.description',
  'dashboard.settings.runtime.entry.publicBlog.eyebrow',
  'dashboard.settings.runtime.entry.publicBlog.title',
  'dashboard.settings.runtime.entry.publicBlog.description',
  'dashboard.settings.runtime.entry.authz.eyebrow',
  'dashboard.settings.runtime.entry.authz.title',
  'dashboard.settings.runtime.entry.authz.description',
  'dashboard.settings.runtime.metrics.eyebrow',
  'dashboard.settings.runtime.metrics.title',
  'dashboard.settings.runtime.metrics.description',
  'dashboard.settings.runtime.metrics.cpuLabel',
  'dashboard.settings.runtime.metrics.cpuHint',
  'dashboard.settings.runtime.metrics.memoryLabel',
  'dashboard.settings.runtime.metrics.memoryHint',
  'dashboard.settings.runtime.metrics.storageLabel',
  'dashboard.settings.runtime.metrics.storageHint',
  'dashboard.settings.runtime.metrics.updatedAt',
  'dashboard.settings.runtime.metrics.unavailable'
);

INSERT INTO `translations` (`locale`, `key`, `value`)
VALUES
  ('tr', 'dashboard.settings.runtime.checklistDescription', 'Runtime cache operasyonlari ve tarayici telemetry sinyalleri ayni yuzeyde toplanir.'),
  ('tr', 'dashboard.settings.runtime.checklistTitle', 'Runtime operator notlari'),
  ('tr', 'dashboard.settings.runtime.description', 'Cache registry''lerini tek tek yenileyebileceginiz ve tarayici telemetry sinyallerini izleyebileceginiz operasyon tab''i.'),
  ('tr', 'dashboard.settings.runtime.cacheKeyLabel', 'Cache anahtari'),
  ('tr', 'dashboard.settings.runtime.cacheScopeLabel', 'Cache kapsami'),
  ('tr', 'dashboard.settings.runtime.cacheStrategyLabel', 'Cache backend'),
  ('tr', 'dashboard.settings.runtime.cacheValueLabel', 'Sicil ozeti'),
  ('tr', 'dashboard.settings.runtime.warmScopeLabel', 'Warm kapsami'),
  ('tr', 'dashboard.settings.runtime.refreshAction', 'Cache Yenile'),
  ('tr', 'dashboard.settings.runtime.refreshPending', 'Yenileniyor'),
  ('tr', 'dashboard.settings.runtime.scope.actor', 'Aktor scope'),
  ('tr', 'dashboard.settings.runtime.scope.global', 'Global scope'),
  ('tr', 'dashboard.settings.runtime.scope.locale', 'Locale bundle'),
  ('tr', 'dashboard.settings.runtime.scope.page', 'Sayfa cache''i'),
  ('tr', 'dashboard.settings.runtime.strategy.cloudflare', 'Cloudflare edge cache'),
  ('tr', 'dashboard.settings.runtime.strategy.memory', 'In-memory fallback'),
  ('tr', 'dashboard.settings.runtime.strategy.none', 'Cache devre disi'),
  ('tr', 'dashboard.settings.runtime.value.keys', '{count} key'),
  ('tr', 'dashboard.settings.runtime.value.locales', '{count} locale'),
  ('tr', 'dashboard.settings.runtime.value.page', 'page-{count}'),
  ('tr', 'dashboard.settings.runtime.value.revision', 'revizyon {count}'),
  ('tr', 'dashboard.settings.runtime.entry.configuration.eyebrow', 'Configuration registry'),
  ('tr', 'dashboard.settings.runtime.entry.configuration.title', 'Configuration cache'),
  ('tr', 'dashboard.settings.runtime.entry.configuration.description', 'Site identity ve appearance parameter kayitlarini purge edip tekrar warm eder.'),
  ('tr', 'dashboard.settings.runtime.entry.i18n.eyebrow', 'Locale registry'),
  ('tr', 'dashboard.settings.runtime.entry.i18n.title', 'I18n cache bundle'),
  ('tr', 'dashboard.settings.runtime.entry.i18n.description', 'Supported locale listesi ile locale message bundle cache''lerini birlikte yeniler.'),
  ('tr', 'dashboard.settings.runtime.entry.publicHome.eyebrow', 'Public surface'),
  ('tr', 'dashboard.settings.runtime.entry.publicHome.title', 'Public home cache'),
  ('tr', 'dashboard.settings.runtime.entry.publicHome.description', 'Anasayfa featured projects ve skills payload''ini tekrar cache''e alir.'),
  ('tr', 'dashboard.settings.runtime.entry.publicProjects.eyebrow', 'Public surface'),
  ('tr', 'dashboard.settings.runtime.entry.publicProjects.title', 'Public projects cache'),
  ('tr', 'dashboard.settings.runtime.entry.publicProjects.description', 'Ilk projects sayfa payload''ini purge edip yeniden olusturur.'),
  ('tr', 'dashboard.settings.runtime.entry.publicBlog.eyebrow', 'Public surface'),
  ('tr', 'dashboard.settings.runtime.entry.publicBlog.title', 'Public blog cache'),
  ('tr', 'dashboard.settings.runtime.entry.publicBlog.description', 'Ilk blog sayfa payload''ini purge edip yeniden olusturur.'),
  ('tr', 'dashboard.settings.runtime.entry.authz.eyebrow', 'Authorization registry'),
  ('tr', 'dashboard.settings.runtime.entry.authz.title', 'Authz claim cache'),
  ('tr', 'dashboard.settings.runtime.entry.authz.description', 'Revision tabanli actor cache anahtarlarini cevirir ve mevcut aktoru yeniden warm eder.'),
  ('tr', 'dashboard.settings.runtime.metrics.eyebrow', 'Canli telemetry'),
  ('tr', 'dashboard.settings.runtime.metrics.title', 'Runtime telemetry'),
  ('tr', 'dashboard.settings.runtime.metrics.description', 'Tarayicidan alinabilen hafiza, depolama ve CPU tahminleri her 5 saniyede bir yenilenir.'),
  ('tr', 'dashboard.settings.runtime.metrics.cpuLabel', 'CPU tahmini'),
  ('tr', 'dashboard.settings.runtime.metrics.cpuHint', 'Mantiksal cekirdek: {cores}'),
  ('tr', 'dashboard.settings.runtime.metrics.memoryLabel', 'JS heap kullanimi'),
  ('tr', 'dashboard.settings.runtime.metrics.memoryHint', 'Heap limiti: {limit}'),
  ('tr', 'dashboard.settings.runtime.metrics.storageLabel', 'Depolama kullanimi'),
  ('tr', 'dashboard.settings.runtime.metrics.storageHint', 'Tarayici kota tahmini: {quota}'),
  ('tr', 'dashboard.settings.runtime.metrics.updatedAt', 'Son guncelleme: {time}'),
  ('tr', 'dashboard.settings.runtime.metrics.unavailable', 'Yok'),
  ('en', 'dashboard.settings.runtime.checklistDescription', 'Runtime cache operations and browser telemetry signals stay on the same surface.'),
  ('en', 'dashboard.settings.runtime.checklistTitle', 'Runtime operator notes'),
  ('en', 'dashboard.settings.runtime.description', 'An operations tab where each cache registry can be refreshed independently and browser telemetry signals stay visible.'),
  ('en', 'dashboard.settings.runtime.cacheKeyLabel', 'Cache key'),
  ('en', 'dashboard.settings.runtime.cacheScopeLabel', 'Cache scope'),
  ('en', 'dashboard.settings.runtime.cacheStrategyLabel', 'Cache backend'),
  ('en', 'dashboard.settings.runtime.cacheValueLabel', 'Registry summary'),
  ('en', 'dashboard.settings.runtime.warmScopeLabel', 'Warm scope'),
  ('en', 'dashboard.settings.runtime.refreshAction', 'Refresh Cache'),
  ('en', 'dashboard.settings.runtime.refreshPending', 'Refreshing'),
  ('en', 'dashboard.settings.runtime.scope.actor', 'Actor scope'),
  ('en', 'dashboard.settings.runtime.scope.global', 'Global scope'),
  ('en', 'dashboard.settings.runtime.scope.locale', 'Locale bundle'),
  ('en', 'dashboard.settings.runtime.scope.page', 'Page cache'),
  ('en', 'dashboard.settings.runtime.strategy.cloudflare', 'Cloudflare edge cache'),
  ('en', 'dashboard.settings.runtime.strategy.memory', 'In-memory fallback'),
  ('en', 'dashboard.settings.runtime.strategy.none', 'Cache disabled'),
  ('en', 'dashboard.settings.runtime.value.keys', '{count} keys'),
  ('en', 'dashboard.settings.runtime.value.locales', '{count} locales'),
  ('en', 'dashboard.settings.runtime.value.page', 'page-{count}'),
  ('en', 'dashboard.settings.runtime.value.revision', 'revision {count}'),
  ('en', 'dashboard.settings.runtime.entry.configuration.eyebrow', 'Configuration registry'),
  ('en', 'dashboard.settings.runtime.entry.configuration.title', 'Configuration cache'),
  ('en', 'dashboard.settings.runtime.entry.configuration.description', 'Purges and warms the site identity and appearance parameter registry.'),
  ('en', 'dashboard.settings.runtime.entry.i18n.eyebrow', 'Locale registry'),
  ('en', 'dashboard.settings.runtime.entry.i18n.title', 'I18n cache bundle'),
  ('en', 'dashboard.settings.runtime.entry.i18n.description', 'Refreshes the supported locale list together with locale message bundles.'),
  ('en', 'dashboard.settings.runtime.entry.publicHome.eyebrow', 'Public surface'),
  ('en', 'dashboard.settings.runtime.entry.publicHome.title', 'Public home cache'),
  ('en', 'dashboard.settings.runtime.entry.publicHome.description', 'Rebuilds the featured projects and skills payload used by the home page.'),
  ('en', 'dashboard.settings.runtime.entry.publicProjects.eyebrow', 'Public surface'),
  ('en', 'dashboard.settings.runtime.entry.publicProjects.title', 'Public projects cache'),
  ('en', 'dashboard.settings.runtime.entry.publicProjects.description', 'Purges and rebuilds the first public projects page payload.'),
  ('en', 'dashboard.settings.runtime.entry.publicBlog.eyebrow', 'Public surface'),
  ('en', 'dashboard.settings.runtime.entry.publicBlog.title', 'Public blog cache'),
  ('en', 'dashboard.settings.runtime.entry.publicBlog.description', 'Purges and rebuilds the first public blog page payload.'),
  ('en', 'dashboard.settings.runtime.entry.authz.eyebrow', 'Authorization registry'),
  ('en', 'dashboard.settings.runtime.entry.authz.title', 'Authz claim cache'),
  ('en', 'dashboard.settings.runtime.entry.authz.description', 'Rotates revision-based actor cache keys and warms the current actor again.'),
  ('en', 'dashboard.settings.runtime.metrics.eyebrow', 'Live telemetry'),
  ('en', 'dashboard.settings.runtime.metrics.title', 'Runtime telemetry'),
  ('en', 'dashboard.settings.runtime.metrics.description', 'Browser-accessible memory, storage, and CPU estimates refresh every 5 seconds.'),
  ('en', 'dashboard.settings.runtime.metrics.cpuLabel', 'CPU estimate'),
  ('en', 'dashboard.settings.runtime.metrics.cpuHint', 'Logical cores: {cores}'),
  ('en', 'dashboard.settings.runtime.metrics.memoryLabel', 'JS heap usage'),
  ('en', 'dashboard.settings.runtime.metrics.memoryHint', 'Heap limit: {limit}'),
  ('en', 'dashboard.settings.runtime.metrics.storageLabel', 'Storage usage'),
  ('en', 'dashboard.settings.runtime.metrics.storageHint', 'Browser quota estimate: {quota}'),
  ('en', 'dashboard.settings.runtime.metrics.updatedAt', 'Updated at: {time}'),
  ('en', 'dashboard.settings.runtime.metrics.unavailable', 'N/A');
