"$schema" = "./node_modules/wrangler/config-schema.json"
name = "paper-enes-ink"
main = "./build/server/index.js"
compatibility_date = "2026-03-15"

[assets]
directory = "./build/client"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "paper-enes-ink-db"
database_id = "00000000-0000-0000-0000-000000000000"
preview_database_id = "00000000-0000-0000-0000-000000000000"

