import type { ServerBuild } from "react-router";
import { createRequestHandler } from "@react-router/cloudflare";

import { createCloudflareLoadContext } from "./load-context";
import type { CloudflareAppBindings } from "./bindings";

// @ts-expect-error Generated by `react-router build` before Wrangler bundles the worker.
import * as serverBuild from "../build/server/index.js";

const build = serverBuild as ServerBuild;

export default createRequestHandler<CloudflareAppBindings>({
  build,
  getLoadContext({ context, request }) {
    return createCloudflareLoadContext({
      env: context.cloudflare.env,
      request,
    });
  },
});
